Issue #101: Onboarding process of Jonathan Lopez
ai-cfia/dev-rel-docs pull request #102
Opened 2024-01-22 21:21 UTC by SonOfLope

Throughout Jonathan Lopez's onboarding, it was noticed that there was room for enhancement in the availability of security training resources.

### Tasks:
- [x] Update time descriptions.
- [x]  Incorporate new DevSecOps/security resources into the training.
### Acceptance Criteria:
- The training should equip the developer with the skills necessary to work within the AI LAB's framework.
- The training should provide accurate time estimates for each module.
### Closes PR:
- Closes #101

2024-01-23 12:56 UTC, rngadam commented
would also appreciate some devsecops links and review of GoC documentation such as:

* https://github.com/canada-ca/cloud-guardrails
* https://www.canada.ca/en/shared-services/corporate/gc-cloud-strategy-2024.html

2024-01-23 12:59 UTC, rngadam requested changes
add GoC documentation

2024-01-23 15:29 UTC, SonOfLope commented
> would also appreciate some devsecops links and review of GoC documentation such as:
> 
> * https://github.com/canada-ca/cloud-guardrails
> * https://www.canada.ca/en/shared-services/corporate/gc-cloud-strategy-2024.html

regarding GC Cloud strategy, it was announced to be published in [march 2024](https://gcxgce.sharepoint.com/teams/1000233/SitePages/Cloud-Strategy-Update-2024.aspx) : 
![image](https://github.com/ai-cfia/dev-rel-docs/assets/73133692/ab31b2c5-ae12-4183-954b-fa287aed95dc)

2024-01-23 19:48 UTC, rngadam commented
@SonOfLope I gave the link to the guardrails too and would want to see some googling to see what else we can find related to devops and GoC. Example:

https://catalogue.csps-efpc.gc.ca/product?catalog=DDN112&cm_locale=en

2024-01-23 20:02 UTC, SonOfLope commented
> @SonOfLope I gave the link to the guardrails too and would want to see some googling to see what else we can find related to devops and GoC. Example:
> 
> https://catalogue.csps-efpc.gc.ca/product?catalog=DDN112&cm_locale=en

Yes I am on that! I will request a new review upon adding new links.

2024-01-29 20:00 UTC, rngadam requested changes

2024-01-29 20:00 UTC, rngadam commented on TRAINING.md
> +  * [GoC Devops
L'école de la fonction publique du Canada n'est pas accessible au public en général; je pense qu'il vaut mieux mettre ce lien dans notre wiki interne.

2024-01-29 20:17 UTC, SonOfLope commented on TRAINING.md
> +  * [GoC Devops
That link was your suggestion. I will remove it.

2024-01-29 20:26 UTC, SonOfLope commented on TRAINING.md
> +  * [GoC Devops
done

2024-01-29 21:16 UTC, rngadam commented on TRAINING.md
> +  * [GoC Devops
> That link was your suggestion. I will remove it.

yup, sometimes I don't give the right specifics but the intent is the same (to have a better DevOps training process for incoming employees and external contributors whether internal or external wiki).

2024-01-29 21:16 UTC, rngadam approved these changes

2024-01-29 21:18 UTC, SonOfLope commented on TRAINING.md
> +  * [GoC Devops
link was added to internal wiki 👍

2024-01-29 21:18 UTC, merged