Explain draft pull request
ai-cfia/dev-rel-docs pull request #106
Opened 2024-01-25 15:46 UTC by MaxenceGui

Explain draft pull request

1. Open an [issue]((https://github.com/ai-cfia/dev-rel-docs/issues)
2. Name it "onboarding process of your name"
3. Use this template:

```
Maxence Guindon onboarding process

Tasks:

* [ ] Update time descriptions.

Acceptance Criteria:

The training should equip the developer with the skills necessary to work within the AI LAB's framework.
The training should provide accurate time estimates for each module.
```
4. Go back on training.md and click edit button on this file 
![image](https://github.com/ai-cfia/dev-rel-docs/assets/96267006/b11677ef-6319-4580-b8f0-f348b0e3854b)
5. Edit the document (example add the time it took you to read value and ethics)
6. Click on commit changes
7. create a branch with this format: issue_number-onboarding-process-your-name (example 42-onboarding-process-happy-gilmor)
8. Click on propose change
9.  On the "Open a pull request" page:
10. Add a title
11. Select draft pull request instead of create pull request

2024-01-30 19:58 UTC, rngadam commented
@MaxenceGui you asked for a review but have this set as draft?

2024-01-30 21:34 UTC, MaxenceGui commented
Change it to ready to be reviewed

2024-02-01 13:59 UTC, rngadam approved these changes

2024-02-12 13:10 UTC, rngadam requested changes
@MaxenceGui cleanup the commits history by doing a rebase on the main branch (not a merge). 14 commits for a few lines changes is a bit much.

2024-02-15 14:12 UTC, MaxenceGui commented
> @MaxenceGui cleanup the commits history by doing a rebase on the main branch (not a merge). 14 commits for a few lines changes is a bit much.

Would the simplest be:
![image](https://github.com/ai-cfia/dev-rel-docs/assets/96267006/71593dd2-ddd4-49b0-8029-e69bfbb3105e)

2024-02-15 16:12 UTC, MaxenceGui commented
@rngadam

Rebase is done. I keep only 3 commit with significant title.

2024-02-15 16:35 UTC, rngadam approved these changes
fix typo first and then merge. notify @SamuelPelletierEvraire that the doc is updated.

2024-02-15 16:35 UTC, rngadam commented on TRAINING.md
> +* Finessse
Finesse

2024-02-15 18:19 UTC, merged