Create handling-exception-notes.md
ai-cfia/dev-rel-docs pull request #114
Opened 2024-03-06 19:27 UTC by MaxenceGui

## Pull request to add handling and raising exceptions in Python training

*  Reference issue #113

- [x] Read and take note on [Real Python Exception Tutorial](https://realpython.com/python-raise-exception/#chaining-exceptions-with-the-from-clause)
- [x] Write the documentation that will guide CFIA Handling and Raising Exception
- [x] Modify TRAINING.md file to add the documentation to the backend developer training

2024-03-18 15:48 UTC, rngadam requested changes

2024-03-18 15:48 UTC, rngadam commented on handling-exception-training.md
> +#### Les Exceptions de groupes
when should we be using group exception? do we expect our developers to use this?

I'd like to have a documentation focused on our practices, not every possible variation.

2024-03-21 02:58 UTC, ibrahim-kabir requested changes

2024-03-21 02:58 UTC, ibrahim-kabir commented on handling-exception-notes.md
> +|:wave: To know more| |:--| |[Pozo Ramos, L. (2023,19 juin). *Python's raise:
This emoji and the table does not display on GitHub when I enable the "Display rich diff" option.
![image](https://github.com/ai-cfia/dev-rel-docs/assets/117961703/31d8f00a-6bc2-42e0-9c23-4710399d1c00)

2024-03-21 02:58 UTC, ibrahim-kabir commented on handling-exception-notes.md
> +🚧 This files is not intended to be push to the main branch of dev-rel-docs.
typo
```suggestion
🚧 This file is not intended to be push to the main branch of dev-rel-docs.
```

2024-03-21 02:58 UTC, ibrahim-kabir commented on handling-exception-notes.md
> +Every exception have a [traceback](https://realpython.com/python-traceback/)
typo

```suggestion
Every exception has a [traceback](https://realpython.com/python-traceback/)
```

2024-03-21 02:58 UTC, ibrahim-kabir commented on handling-exception-notes.md
> +    print("Your list doesn't have that index :-(")
syntax error

```suggestion
try:
    colors[10]
except IndexError:
    print("Your list doesn't have that index :-(")
```

2024-03-21 02:58 UTC, ibrahim-kabir commented on handling-exception-notes.md
> +> If your note using from the message will be different. Without `from`, the
typo

```suggestion
> If you're not using `from`, the message will be different. Without `from`, the
```

2024-03-21 13:52 UTC, MaxenceGui commented on handling-exception-notes.md
> +|:wave: To know more| |:--| |[Pozo Ramos, L. (2023,19 juin). *Python's raise:
Done

2024-03-21 13:52 UTC, MaxenceGui commented on handling-exception-notes.md
> +🚧 This files is not intended to be push to the main branch of dev-rel-docs.
Done

2024-03-21 13:53 UTC, MaxenceGui commented on handling-exception-notes.md
> +Every exception have a [traceback](https://realpython.com/python-traceback/)
Done

2024-03-21 13:55 UTC, MaxenceGui commented on handling-exception-notes.md
> +    print("Your list doesn't have that index :-(")
Done

2024-03-21 13:55 UTC, RussellJimmies requested changes

2024-03-21 13:55 UTC, RussellJimmies commented on handling-exception-notes.md
> +🚧 This files is not intended to be push to the main branch of dev-rel-docs.
to be pushed

2024-03-21 13:55 UTC, MaxenceGui commented on handling-exception-notes.md
> +> If your note using from the message will be different. Without `from`, the
Done

2024-03-21 13:56 UTC, MaxenceGui commented on handling-exception-notes.md
> +🚧 This files is not intended to be push to the main branch of dev-rel-docs.
Done

2024-03-21 13:56 UTC, MaxenceGui commented on handling-exception-notes.md
> +It's just to give a chance for everyone to review the note I took 🚧
Done

2024-03-21 13:56 UTC, MaxenceGui commented on handling-exception-notes.md
> +Every exception have a [traceback](https://realpython.com/python-traceback/)
Done

2024-03-21 13:57 UTC, MaxenceGui commented on handling-exception-notes.md
> +|:warning:| Raising `Exception` instance is not considered best practice.|
Done

2024-03-21 13:57 UTC, MaxenceGui commented on handling-exception-notes.md
> +attribute, also name:
Done

2024-03-21 15:00 UTC, ibrahim-kabir approved these changes

2024-03-25 22:54 UTC, k-allagbe approved these changes
Informative. Never really paid attention to exception message formatting before. 👍

2024-04-02 14:07 UTC, rngadam requested changes
Suggest removing the -notes.md and splitting the french and english into two markdowns (handling-exception-training.md and handling-exception-training.fr-ca.md) as it's a bit unwieldy to have both in the same file.

2024-04-02 17:33 UTC, MaxenceGui commented
> Suggest removing the -notes.md and splitting the french and english into two markdowns (handling-exception-training.md and handling-exception-training.fr-ca.md) as it's a bit unwieldy to have both in the same file.

Implement your change

2024-04-03 16:28 UTC, rngadam approved these changes

2024-04-09 14:20 UTC, MaxenceGui commented
@RussellJimmies if it's ok with you, we can merge these files and open an issue to review and correct their grammar since they are big files.

2024-04-09 20:31 UTC, RussellJimmies approved these changes

2024-04-09 20:45 UTC, merged