issue #30: documented naming convention
ai-cfia/dev-rel-docs pull request #31
Opened 2023-09-20 18:37 UTC by k-allagbe

#30
issue30-naming-conventions

added general convention and example for usual CLI accessible resources

Closes #30

2023-09-20 18:50 UTC, rngadam requested changes

2023-09-20 18:50 UTC, rngadam commented on Naming-Conventions/NAMING-RESOURCES.md
> +- **Example**: `REPO_NAME_MY_ENV_VAR`
PROJECT_NAME and not REPO_NAME; we don't want 

MEMBRANE_BACKEND_ENVIRONMENT_VARIABLE 

...but:

MEMBRANE_ENVIRONMENT_VARIABLE.

we don't want to have to go back changing environment variable name if we moved from backend to frontend (in a fat client for example...)

2023-09-20 18:50 UTC, rngadam commented on Naming-Conventions/NAMING-RESOURCES.md
> +- **Example**: `my-project-storage-account`
project-storage-account

no doubt someone is going to interpret this as needing prefix my

maybe best would be to use bash environment variables so we have

PROJECT_NAME: your project name / codename such as membrane, nachet, louis, etc...

$(PROJECT_NAME)-storage-account

so for PROJECT_NAME=nachet and a storage account we have:

```
nachet-storage-account
```

2023-09-20 18:50 UTC, rngadam commented on Naming-Conventions/NAMING-RESOURCES.md
> +
there are also a twist on SQL files where we require prefix 

`YYYY-mm-dd-description-of-script.sql`

see: https://github.com/ai-cfia/louis-db/tree/main/sql

2023-09-20 18:51 UTC, rngadam commented on Naming-Conventions/NAMING-RESOURCES.md
> +- **Example**: `my-project-storage-account`
expressed in shell-speak:

```
$ PROJECT_NAME=nachet; echo $PROJECT_NAME-storage-account
nachet-storage-account
```

2023-09-25 19:07 UTC, k-allagbe commented on Naming-Conventions/NAMING-RESOURCES.md
> +- **Example**: `REPO_NAME_MY_ENV_VAR`
done

2023-09-25 19:08 UTC, k-allagbe commented on Naming-Conventions/NAMING-RESOURCES.md
> +- **Example**: `my-project-storage-account`
done

2023-09-25 19:08 UTC, k-allagbe commented on Naming-Conventions/NAMING-RESOURCES.md
> +
done

2023-09-25 19:23 UTC, rngadam approved these changes

2023-09-25 19:27 UTC, merged