add intake file
ai-cfia/dev-rel-docs pull request #38
Opened 2023-09-29 16:12 UTC by redat97

Created an intake file checklist which helps keep track of progress of products as well as making sure necessary files are present

2023-09-29 16:13 UTC, redat97 commented
I also thought we could add mutation tests for the code testing but I'm not sure if that is a good or bad idea

2023-09-29 17:48 UTC, rngadam commented
@redat97 I added to the project DevOps. Don't forget to add DevOps related issues to your DevOps project and stack ranking the tasks there.

2023-09-29 17:57 UTC, rngadam requested changes

2023-09-29 17:57 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +  * https://github.com/orgs/ai-cfia/projects/2
this was specific to the intake of Louis...

2023-09-29 17:57 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +* [ ] a Project to manage this product has been created
a [Github Project](https://github.com/orgs/ai-cfia/projects)

fill-in the details and augment with links from the draft I gave you.

2023-09-29 17:57 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +    * [ ] Explain the purpose of the product
Can replace these by:

 refer to :
 
 * Internal AI Project intake is documented on the internal Wiki
 * criterias for internal AI product is documented on the internal Wiki

2023-09-29 17:57 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   * [ ] of daily active users
link each step to the relevant documentation for the implementation or add sections below here.

* link to github-workflows documentation
* link to gcp deployment documentation
* link to setting up repository and organization secrets
* link to configuration of the Github repository (ex: protect branch main by requiring one approval)

2023-09-29 17:57 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +* [ ] code testing
you have tests documentation in developer documentation, code testing and test documentation. Regroup in a single testing group

2023-10-01 15:38 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +  * https://github.com/orgs/ai-cfia/projects/2
removed and changed to main url my mistake

2023-10-01 15:41 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +* [ ] a Project to manage this product has been created
I am not totally sure what you mean by that the only link that was in the draft was the one pointing to the louis project

2023-10-01 15:41 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +    * [ ] Explain the purpose of the product
done

2023-10-01 15:48 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +   * [ ] of daily active users
done but please look at my comment

2023-10-01 15:48 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +* [ ] code testing
done

2023-10-01 15:55 UTC, redat97 commented
We currently have a situation where our project is open source and includes a checklist with points like "Internal AI Project intake is documented on the internal Wiki", however, the wiki is hosted on a private page. I put myself in the place of someone who is looking to work on this open source project and sees links to pages he cannot acces like the configuration of the Github repository which is in the private wiki. I am having trouble understanding if this list is for the CFIA or for public use

2023-10-02 12:59 UTC, rngadam requested changes

2023-10-02 12:59 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   * [ ] Internal AI Project intake and criteria for internal AI products [documented on the internal Wiki](https://dev.azure.com/CFIA-DevOps-ACIA/AI-Lab/_wiki/wikis/AI-Lab.wiki/689/AI-Lab-Wiki-HomeP
I just want you to mention this, you don't link it.

2023-10-02 12:59 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   * [ ] [Repository main branch Security Configured](https://dev.azure.com/CFIA-DevOps-ACIA/AI-Lab/_wiki/wikis/AI-Lab.wiki/1012/Creating-a-GitHub-repository).
Move this page to the devops repo

2023-10-02 12:59 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   * [ ] [Repository main branch Security Configured](https://dev.azure.com/CFIA-DevOps-ACIA/AI-Lab/_wiki/wikis/AI-Lab.wiki/1012/Creating-a-GitHub-repository).
this doc will not just talk about the main branch protect, so this should be described as "Configure repository to our own internal standards".

2023-10-02 12:59 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +* [ ] **Project Initialization and Documentation**
As with any other document, you need to start with a blurb under Context, Introduction and/or Pre-requisites heading to explain purpose/context

2023-10-02 13:41 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +* [ ] **Project Initialization and Documentation**
are you able to see my comments? I left two and you didn't answer, I feel like I brought up a good point and I am not totally sure how I should introduce the file. If I say this is a checklist for general use then it feels wrong to me to have checkmarks for things the user has no control over or is it for the user to follow along the progress of the project on our end but I still find it weird to have checkmarks on files or items they don't have access to if you can clear this out for me so that I make a good introduction and explain the purpose correctly

2023-10-02 13:55 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +   * [ ] [Repository main branch Security Configured](https://dev.azure.com/CFIA-DevOps-ACIA/AI-Lab/_wiki/wikis/AI-Lab.wiki/1012/Creating-a-GitHub-repository).
done

2023-10-02 13:55 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +   * [ ] Internal AI Project intake and criteria for internal AI products [documented on the internal Wiki](https://dev.azure.com/CFIA-DevOps-ACIA/AI-Lab/_wiki/wikis/AI-Lab.wiki/689/AI-Lab-Wiki-HomeP
done

2023-10-02 14:06 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +* [ ] **Project Initialization and Documentation**
I added an introduction context and pre-requisites if they are fine we can leave them as they are I hope I don't give the impression I'm stubborn just wanna make sure I 100% understand what I'm asked to do

2023-10-02 14:12 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +* [ ] **Project Initialization and Documentation**
The checklist is for you, the devops, to complete. Any product in this organization will have an employee-developer attached to it so they are able to follow these instructions even if we receive contributions from external developers.

2023-10-02 14:20 UTC, rngadam requested changes

2023-10-02 14:20 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +- You have read and understood the guidelines and objectives outlined in each section.
I would add something first to the list: you've completed a project to prototype a software solution and are now ready to turn it into a production-ready product.

2023-10-02 17:25 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +* [ ] code testing
> You named it "Code and Testing" but it's just Testing. You still have "tests documentation" under developer documentation; maybe you meant "Running the test suite". Here we should have a Manual test plan.

I think this comment is not addressed

2023-10-02 17:25 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   * [ ] [Repository main branch Security Configured](https://dev.azure.com/CFIA-DevOps-ACIA/AI-Lab/_wiki/wikis/AI-Lab.wiki/1012/Creating-a-GitHub-repository).
@redat97

2023-10-02 17:26 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +* [ ] code testing
no not yet I converted is a draft I don't know why you got a notification but I was going to ask you is the manual test plan not the integration tests?

2023-10-02 17:28 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +   * [ ] [Repository main branch Security Configured](https://dev.azure.com/CFIA-DevOps-ACIA/AI-Lab/_wiki/wikis/AI-Lab.wiki/1012/Creating-a-GitHub-repository).
converted it as a draft I don't know why you are getting notifications

2023-10-02 17:53 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +   * [ ] [Repository main branch Security Configured](https://dev.azure.com/CFIA-DevOps-ACIA/AI-Lab/_wiki/wikis/AI-Lab.wiki/1012/Creating-a-GitHub-repository).
I created a PR in the devops repository I wasn't sure if you wanted to review it just in case or not

2023-10-02 19:50 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +* [ ] code testing
ok, made the changes then

2023-10-03 12:44 UTC, rngadam requested changes

2023-10-03 12:44 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   * [ ] **Testing**
ajouté un bullet point et gardé l'ancien...

2023-10-03 12:44 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +* [ ] code testing
please review my comment

2023-10-03 12:44 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   * [ ] Configure repository to our own internal standards.
link to the new doc

2023-10-03 12:44 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   > - [Understanding GitHub Actions](https://docs.github.com/fr/actions/learn-github-actions/understanding-github-actions)
links to general documentation go into separate heading references

2023-10-03 12:44 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   * [ ] Continuous lint, test, build, and deployment pipeline established.
link to our reusable github workflow setup

2023-10-03 17:01 UTC, rngadam requested changes

2023-10-03 17:01 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   * [ ] Continuous lint, test, build, and deployment pipeline established.
this one has been modified to add a whitespace at the end of the line. make sure your editor is stripping extraneous whitespaces when saving (and make sure our doc explains how to configure this in visual studio code)

2023-10-03 17:28 UTC, redat97 commented on DevOps-documentation/devops-intake.md
>     * [ ] Setup and installation guide.
I meant the project's setup and installation guide it changes from project to project no?

2023-10-03 17:30 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +   * [ ] Configure repository to our own internal standards.
you need to accept the PR so I can have a link to it from the main

2023-10-03 19:06 UTC, rngadam requested changes

2023-10-03 19:06 UTC, rngadam commented on DevOps-documentation/devops-intake.md
>     * [ ] Setup and installation guide.
ok

2023-10-03 19:06 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   * [ ] Unit test suite implemented with a minimum of X% code coverage.
seems to be shorter than this morning...

2023-10-03 19:10 UTC, rngadam commented
Your title, description and commits don't contain references to the issue @redat97 ; you have to set the example for developers by following the process.

2023-10-03 19:13 UTC, redat97 commented
> Your title, description and commits don't contain references to the issue @redat97 ; you have to set the example for developers by following the process.

I have no idea why I didn't do that in the first place I'll make sure of it from now one

2023-10-03 19:58 UTC, rngadam requested changes

2023-10-03 19:58 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   <br/><br/>
do not use br (or any html tags)

create new headings instead

## references

## resources

2023-10-03 20:02 UTC, redat97 commented on DevOps-documentation/devops-intake.md
> +   <br/><br/>
I just removed them it was unnecessary

2023-10-03 20:14 UTC, rngadam requested changes

2023-10-03 20:14 UTC, rngadam commented on DevOps-documentation/devops-intake.md
> +   > **References:**
move references and resources to a single section at the bottom:

## Resources

I want to be able to copy/paste the checklist to a new github issues without extraneous doc getting copied over.

2023-10-03 21:12 UTC, rngadam approved these changes

2023-10-03 23:27 UTC, merged