issue #41: adr for adopting adr
ai-cfia/dev-rel-docs pull request #44
Opened 2023-10-12 16:19 UTC by k-allagbe

Fixes #41 - ADR on Adopting ADRs

2023-10-12 17:00 UTC, rngadam requested changes

2023-10-12 17:00 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +
What should ADR contain? What should they not contain?

2023-10-12 17:00 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +- Inconsistent architectural approaches across different parts of the project
List alternatives

2023-10-12 20:03 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +Accepted
Removed status altogether because version control implicitly manages the status.

2023-10-12 20:04 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +AI-Lab has been facing challenges in maintaining a clear and understandable history of architectural decisions. As the team grows and the codebase expands, it becomes increasingly difficult to keep t
Done.

2023-10-12 20:04 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- ADR history will be managed through GitHub's version history.
Done.

2023-10-12 20:05 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- New team members can easily get up to speed by reviewing the ADR's version history.
Done

2023-10-12 20:05 UTC, k-allagbe commented on README.md
> +**[ADR: AI-Lab using ADR](./adr/001-ailab-using-adr.md)** - Why we decided to use Architectural Decision Records.
Done. Called it index.md.

2023-10-12 20:05 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +
Done

2023-10-12 20:06 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- Inconsistent architectural approaches across different parts of the project
Done. Might need further discussion though.

2023-10-13 14:28 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- **Architecture Decision Records (ADRs)**: ADRs offer a version-controlled way to document decisions, making them easily accessible and up-to-date. They also allow for concise documentation of the c
- Architecture Decision Records (ADRs): 
    - version-controlled way to document decisions
    - easily accessible and up-to-date
    - concise documentation of the context, decision, and consequences.

2023-10-13 14:31 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- Sections will include: Context, Decision, Consequences, and optionally, References.
References are mandatory.

2023-10-13 15:27 UTC, redat97 approved these changes

2023-10-13 15:37 UTC, RussellJimmies approved these changes

2023-10-13 19:49 UTC, rngadam requested changes

2023-10-13 19:49 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +- Could be considered over-engineered for very small or short-term projects
these two cons are not relevant to us as we already have version control and we're doing longer term projects. find more relevant cons.

2023-10-13 19:49 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +3. In the new branch, create a new ADR with a new number but retain the original tag. This new ADR should reference the old one.
use indent to show these bullet points are sub-steps to step 2

2023-10-13 19:49 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +
Provide a list of example questions that could be answered by ADR vs a list of questions that should not be answered by ADRs

2023-10-16 16:28 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- Could be considered over-engineered for very small or short-term projects
Done

2023-10-16 16:29 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +
Done. These need review though. Especially the should not list.

2023-10-16 18:55 UTC, rngadam requested changes
review with this (suggested by @JolanThomassin ):

https://github.com/joelparkerhenderson/architecture-decision-record

can you find a way to format your paragraphs in markdown so that they wrap on column 80?

2023-10-16 18:55 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +- Proposed: ADRs or modifications proposed via active pull requests and placed in the `adr/` folder.
uppercase all the state 

- PROPOSED: ...
- ACCEPTED: ...
- ...

2023-10-16 18:55 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +- Code style and formatting rules.
this could be an ADR; I think the criteria is, does the question apply to a wide slice of our projects/products and must be respected by individual teams?

2023-10-16 18:55 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +- Choice of specific IDEs or development tools.
this could be an ADR I think. At least, a decision has been made to standardize on VSC only whereas some teams might allow the development environment of your choice.

2023-10-17 10:23 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- Proposed: ADRs or modifications proposed via active pull requests and placed in the `adr/` folder.
Done

2023-10-17 10:23 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- Code style and formatting rules.
Done

2023-10-17 10:23 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- Choice of specific IDEs or development tools.
Done

2023-10-17 12:13 UTC, rngadam requested changes
@k-allagbe LGTM but let's get everybody in the team to write at least one ADR based on your documentation to test it.

2023-10-17 12:13 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +
extra whileline here?

2023-10-17 13:48 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +
Done

2023-10-17 18:33 UTC, rngadam approved these changes

2023-10-17 18:34 UTC, rngadam commented
@nmeraihi please review our first important decision through ADR.

2023-10-17 19:16 UTC, k-allagbe commented
As discusses with the team I added an "abstract" section.

2023-10-17 20:17 UTC, melanie-fressard commented on adr/001-ailab-using-adr.md
> +This ADR establishes the use of ADRs within AI-Lab at CFIA for documenting key architectural decisions. We chose ADRs for their version-controlled, clear, and accessible format, addressing issues suc
Should we put it in italics to show its different from the rest ?

2023-10-17 20:17 UTC, melanie-fressard commented on adr/001-ailab-using-adr.md
> +- Requires ongoing discipline to maintain and update records
You're not consistent with the use of ".", either put one at every end of sentences or none at all

2023-10-17 20:17 UTC, melanie-fressard commented on adr/001-ailab-using-adr.md
> +deemed too trivial for ADR documentation.
I think criteria should end with an s here

2023-10-17 20:17 UTC, melanie-fressard commented on adr/001-ailab-using-adr.md
> +- Sections will include: Context, Decision, Consequences and References.
Add Abstract

2023-10-17 20:44 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- Sections will include: Context, Decision, Consequences and References.
Done

2023-10-17 20:44 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- Requires ongoing discipline to maintain and update records
Done

2023-10-17 20:45 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +This ADR establishes the use of ADRs within AI-Lab at CFIA for documenting key architectural decisions. We chose ADRs for their version-controlled, clear, and accessible format, addressing issues suc
In my opinion it's not necessary. Let's hear about the others.

2023-10-17 20:47 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +deemed too trivial for ADR documentation.
Thank you for pointing it out. Criteria is actually the plural form.

2023-10-18 07:07 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +This ADR establishes the use of ADRs within AI-Lab at CFIA for documenting key architectural decisions. We chose ADRs for their version-controlled, clear, and accessible format, addressing issues suc
@melanie-fressard I'd rather we limit formatting of text in a markdown to keep readability of the source markdown file high

2023-10-18 07:12 UTC, rngadam requested changes

2023-10-18 07:12 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +Food Inspection Agency (CFIA), is dedicated to leveraging AI technologies to
expand acronym the first time it appears in the document. Here, this is the second instance.

2023-10-18 07:12 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +### What is an ADR?
isn't this weird that this explanation comes after the decision? I'd move it at the top after context.

2023-10-18 14:13 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +Food Inspection Agency (CFIA), is dedicated to leveraging AI technologies to
Done

2023-10-18 15:21 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +### What is an ADR?
Done

2023-10-18 15:58 UTC, rngadam requested changes

2023-10-18 15:58 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +- Sections will include: Abstract, Context, Decision, Consequences and
let's create a template 001-ailab-using-adr-template.md (issue #55)

as discussed with @JolanThomassin , we also want to have attachment in the same name prefixes. for example, adding a diagram (if there was one associated to an ADR) should be done as:  001-ailab-using-adr-diagram.png

This is instead of using the dragndrop assets creation of Github - allowing offline editing and exporting to different wiki solutions.

2023-10-18 16:42 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +- Sections will include: Abstract, Context, Decision, Consequences and
Done. I updated the `Format` section to mention it. I also added a 001-ailab-using-adr-template.md and updated the index.md with it. Should the ADR reference the attachments?

2023-10-18 21:18 UTC, melanie-fressard approved these changes
Good job, small changes and its good for me :)

2023-10-18 21:18 UTC, melanie-fressard commented on adr/001-ailab-using-adr-template.md
> +# Title
change title to ADR XX : Title

2023-10-18 21:18 UTC, melanie-fressard commented on adr/001-ailab-using-adr-template.md
> +Add as many alternatives as necessary
Missing a .

2023-10-18 21:18 UTC, melanie-fressard commented on adr/001-ailab-using-adr-template.md
> +The context section sets the stage and provides background information necessary
would put an s at information

2023-10-18 21:18 UTC, melanie-fressard commented on adr/index.md
> +**[ADR 1 - Attachment: ADR Template](./adr/001-ailab-using-adr-template.md)** - Template used for ADRs in the AI-Lab.
Maybe call it adr 00 so that it shows its a template ?

2023-10-18 21:24 UTC, k-allagbe commented on adr/001-ailab-using-adr-template.md
> +# Title
Done

2023-10-18 21:24 UTC, k-allagbe commented on adr/001-ailab-using-adr-template.md
> +Add as many alternatives as necessary
Done

2023-10-18 21:26 UTC, k-allagbe commented on adr/001-ailab-using-adr-template.md
> +The context section sets the stage and provides background information necessary
Another strange plural word 😅.

2023-10-18 21:27 UTC, k-allagbe commented on adr/index.md
> +**[ADR 1 - Attachment: ADR Template](./adr/001-ailab-using-adr-template.md)** - Template used for ADRs in the AI-Lab.
I'd vote to keep it this way. Let's hear about the others.

2023-10-19 11:30 UTC, redat97 commented on adr/001-ailab-using-adr-template.md
> +decision, stakeholders involved, and current circumstances.
I might be wrong but does the agency have stakeholders?

2023-10-19 13:03 UTC, melanie-fressard commented on adr/001-ailab-using-adr.md
> +This ADR establishes the use of ADRs within AI-Lab at CFIA for documenting key architectural decisions. We chose ADRs for their version-controlled, clear, and accessible format, addressing issues suc
ok, I'll change mine then

2023-10-19 14:07 UTC, redat97 commented on adr/001-ailab-using-adr.md
> +## References
problem is how do you link forums for example or official documentation both don't have official authors

2023-10-19 14:12 UTC, redat97 commented on adr/index.md
> +**[ADR 1 - Attachment: ADR Template](./adr/001-ailab-using-adr-template.md)** - Template used for ADRs in the AI-Lab.
I would just title it adr template personally no number

2023-10-19 14:14 UTC, redat97 commented on adr/index.md
> +**[ADR 1 - Attachment: ADR Template](./adr/001-ailab-using-adr-template.md)** - Template used for ADRs in the AI-Lab.
nvm I just read Ricky's comment about attachments

2023-10-19 14:15 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +## References
As discussed with @rngadam, we want to limit formatting to keep the ADRs as simple as possible.

2023-10-19 20:49 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +- Sections will include: Abstract, Context, Decision, Consequences and
I saw you linked the template. that is correct. thanks.

2023-10-19 20:50 UTC, rngadam approved these changes
LGTM. Would like to have it reviewed by Noureddine.

2023-10-23 17:09 UTC, JolanThomassin commented on adr/001-ailab-using-adr.md
> +# ADR 1: Adopting Architecture Decision Records
Would have called that `ADR 001: Adopting Architecture Decision Records` to be more clear

2023-10-23 17:09 UTC, CFIALeronB approved these changes

2023-10-23 17:15 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +# ADR 1: Adopting Architecture Decision Records
Useful indeed for managing files. But not so much inside the text in my opinion. Let's hear about the others.

2023-10-23 18:13 UTC, leejaeka approved these changes

2023-10-23 20:54 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +# ADR 1: Adopting Architecture Decision Records
I would do ADR-001 to make it clear it's an identifier. if we ever make more than a thousand ADR, it will be easier to renumber too by script ;-)

2023-10-23 21:12 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +# ADR 1: Adopting Architecture Decision Records
Got it. Done

2023-10-23 21:15 UTC, rngadam approved these changes
missing approval from @JolanThomassin and @nmeraihi

2023-10-23 22:21 UTC, nmeraihi commented on adr/001-ailab-using-adr.md
> +
### Definitions:
-  Sould we consider including a **Definitions section** at the beginning to clarify key terms and acronyms. For example  “Pull Requests (PRs)”, “Version Control” ... Just for this ADR for ADRs.

2023-10-23 22:33 UTC, nmeraihi requested changes

2023-10-23 22:33 UTC, nmeraihi commented on adr/001-ailab-using-adr.md
> +
### Roles and Responsibilities:

Maybe we need to have a section that clearly outlines the roles and responsibilities of different stakeholders in the ADR process. For example who is responsible for drafting, reviewing, approving, and modifying ADRs ...

2023-10-23 22:33 UTC, nmeraihi commented on adr/001-ailab-using-adr.md
> +- Must be approved by the whole team before merging.
Let's then inlcude a decsion action to make at our team meeting

2023-10-23 22:33 UTC, nmeraihi commented on adr/001-ailab-using-adr.md
> +
### Conflict Resolution:
- Outline a clear conflict resolution process for disagreements on architectural decisions. In cases where there are disagreements or conflicts regarding an architectural decision, it may be helpful to outline a clear conflict resolution process.

2023-10-24 01:30 UTC, nmeraihi commented on adr/001-ailab-using-adr.md
> +
Just realized that we should also review the linguistic part of the ADR. 

- Language: All ADRs should be written in English to maintain uniformity and to cater to a broader audience. Eventually French version should be provided

- Clarity and Simplicity: Strive for clarity and simplicity in language.

- Proofreading: Before finalizing an ADR, have it proofread to catch any linguistic or grammatical errors (Antidote)

2023-10-24 13:28 UTC, rngadam requested changes

2023-10-24 13:28 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +
maybe clarify how we will publish translated version. I would suggest 001-ailab-using-adr.fr-ca.md (using ISO 639-1 standard language codes)

2023-10-24 14:25 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +
everyone that is currently member of the ai-cfia Github organization and approval is by consensus (approval from all members of the ai-cfia Github organization.

2023-10-24 14:26 UTC, rngadam commented on adr/001-ailab-using-adr.md
> +
we wouldn't merge in an ADR with which a member strongly disagrees

2023-10-24 14:45 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +
Sounds good to me. We probably should then make sure all the team members are present in the GitHub organization.

2023-10-24 14:51 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +
Sounds good. How about absences, like a member in vacation?

2023-10-24 18:56 UTC, redat97 commented on adr/001-ailab-using-adr.md
> +
if non technical people are going to read this it would make sense forsure

2023-10-24 18:59 UTC, melanie-fressard commented on adr/001-ailab-using-adr.md
> +
sounds good, so every ADR should have a link to this adr to be able to consult the "index" ?

2023-10-24 19:49 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +
No just this one. I should have read the whole comment.

2023-10-24 22:19 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +
Done.

2023-10-24 22:21 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +
Done. See `Responsibilities, Creation and Update Process` section.

2023-10-24 22:22 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +
Done. See `Responsibilities, Creation and Update Process` section.

2023-10-24 22:23 UTC, k-allagbe commented on adr/001-ailab-using-adr.md
> +
Done. I used the suffix `.fr-ca` for now.

2023-10-25 15:21 UTC, nmeraihi commented on adr/001-ailab-using-adr.fr-ca.md
> +- Prend en charge le texte enrichi et les multimédias pour une documentation
Are we writing ADRs in both official lang?

2023-10-25 17:15 UTC, JolanThomassin commented on adr/001-ailab-using-adr.fr-ca.md
> +- Prend en charge le texte enrichi et les multimédias pour une documentation
It's a good think to have both EN and FR files, maybe create store them in separate folder ? Something like this
- ADR
  - EN_ADR
  - FR_ADR

2023-10-25 17:15 UTC, JolanThomassin approved these changes

2023-10-25 20:23 UTC, rngadam approved these changes

2023-10-30 21:07 UTC, rngadam commented on adr/001-ailab-using-adr.fr-ca.md
> +- Prend en charge le texte enrichi et les multimédias pour une documentation
@JolanThomassin we're detailed how we want to do it in ADR-001

2023-10-30 21:11 UTC, rngadam approved these changes

2023-11-02 01:56 UTC, nmeraihi approved these changes

2023-11-02 01:56 UTC, nmeraihi commented on adr/001-ailab-using-adr.fr-ca.md
All good to me

2023-11-02 15:15 UTC, merged