Issue#45 Write an ADR about why we do open-source development
ai-cfia/dev-rel-docs pull request #47
Opened 2023-10-13 16:41 UTC by RussellJimmies

#45

2023-10-13 17:11 UTC, k-allagbe approved these changes
Concise.

Don't forget to rebase on the PR #41 and update the `index.md` file before merging.


Side consideration: add a descriptive tag to your branch names.

2023-10-16 16:27 UTC, rngadam requested changes

2023-10-17 20:34 UTC, RussellJimmies commented on adr/004-opensource-development.md
> +
Done

2023-10-18 07:04 UTC, rngadam commented on adr/004-opensource-development.md
> +The AI Lab is deliberating on the value proposition and risks of open-source development in government artificial intelligence projects. The goal is to ensure that we align our development efforts wi
@RussellJimmies you marked this as resolved but I don't see the fix

2023-10-18 23:24 UTC, rngadam commented
@RussellJimmies I keep getting notified for review requested but I see some of the conversations haven't been addressed yet. Can you convert it to draft until you've addressed the required changes?

2023-10-19 17:39 UTC, RussellJimmies commented on adr/004-opensource-development.md
> +The AI Lab is deliberating on the value proposition and risks of open-source development in government artificial intelligence projects. The goal is to ensure that we align our development efforts wi
Done

2023-10-19 17:39 UTC, RussellJimmies commented on adr/004-opensource-development.md
> +Furthermore, our current technological landscape is heavily interwoven with open-source tools. The Government of Canada has also shown a commitment towards experimentation and open development, as re
Done

2023-10-19 17:39 UTC, RussellJimmies commented on adr/004-opensource-development.md
> +Open source development offers numerous advantages including:
Done

2023-10-19 21:10 UTC, rngadam requested changes
format to linewrap at column 80.

Also write a blurb on how we handle sensitive data (public development vs private deployment)

2023-10-19 21:10 UTC, rngadam commented on adr/004-opensource-development.md
> +The Canadian Food Inspection Food Agency (CFIA) Artificial Intelligence Lab's (AI Lab) mission is to push the boundaries of what AI is capable of doing. Our goal is to make it more accessible to CFIA
our mission is more in-line with "applied AI to the needs of the agency". we're an applied lab, not a research lab.

2023-10-19 21:10 UTC, rngadam commented on adr/004-opensource-development.md
> +After extensive evaluation, we have chosen to adopt the Full Open Source Development approach.
don't need "After extensive evaluation,"

2023-10-19 21:10 UTC, rngadam commented on adr/004-opensource-development.md
> +Every project undertaken by the AI Lab will be released publicly, embracing the ethos of open source development at its core. This means every aspect of our development – from core functionalities to
Every software product

2023-10-20 18:50 UTC, RussellJimmies commented on adr/004-opensource-development.md
> +The Canadian Food Inspection Food Agency (CFIA) Artificial Intelligence Lab's (AI Lab) mission is to push the boundaries of what AI is capable of doing. Our goal is to make it more accessible to CFIA
Reworded the context to reflect that

2023-10-20 18:50 UTC, RussellJimmies commented on adr/004-opensource-development.md
> +After extensive evaluation, we have chosen to adopt the Full Open Source Development approach.
Done

2023-10-20 18:50 UTC, RussellJimmies commented on adr/004-opensource-development.md
> +Every project undertaken by the AI Lab will be released publicly, embracing the ethos of open source development at its core. This means every aspect of our development – from core functionalities to
Done

2023-10-20 18:51 UTC, RussellJimmies commented
Converted to Draft, haven't formatted to linewrap at column 80

2023-10-23 19:41 UTC, rngadam requested changes
line-wrap your paragraph

2023-10-24 20:52 UTC, rngadam requested changes

2023-10-24 20:52 UTC, rngadam commented on adr/004-open-source-development.md
> +and collaboration right from the inception of any project.
product

2023-10-25 00:34 UTC, RussellJimmies commented on adr/004-open-source-development.md
> +and collaboration right from the inception of any project.
Done

2023-10-25 18:54 UTC, rngadam requested changes

2023-10-25 18:54 UTC, rngadam commented on adr/004-open-source-development.md
> +* [Government of Canada Digital Standards:
Couple more references to pages from well known organizations (Microsoft, OSI, FSF) on the "why Open Source"

2023-10-30 20:28 UTC, rngadam requested changes

2023-10-30 20:28 UTC, rngadam commented on adr/004-opensource-development.md
> +Furthermore, our current technological landscape is heavily interwoven with open-source tools. The Government of Canada has also shown a commitment towards experimentation and open development, as re
add an heading explaining how we decided to standardize on open source into the ADR

2023-10-30 20:28 UTC, rngadam commented on adr/004-open-source-development.md
> +Moreover, Microsoft, who was opposed to the open source paradigm considering it a threat to its business, changed its stance significantly around 2010 when it began to embrace it. The company recogni
this paragraph is not wrapped

2023-10-30 20:28 UTC, rngadam commented on adr/004-open-source-development.md
> +Finally, it's important to understand that "open source" doesn't solely refer to source code access, software must comply with the [Open Source Initiative's criteria](#ref3) to be **truly** open sour
this paragraph is not wrapped

2023-10-31 13:42 UTC, RussellJimmies commented on adr/004-open-source-development.md
> +Moreover, Microsoft, who was opposed to the open source paradigm considering it a threat to its business, changed its stance significantly around 2010 when it began to embrace it. The company recogni
Done

2023-10-31 13:42 UTC, RussellJimmies commented on adr/004-open-source-development.md
> +Finally, it's important to understand that "open source" doesn't solely refer to source code access, software must comply with the [Open Source Initiative's criteria](#ref3) to be **truly** open sour
Done

2023-10-31 18:18 UTC, melanie-fressard requested changes
There is a few format problems, you should re format it and it should be fine :) 
Good job, hype to know how to do the ref thingy

2023-10-31 18:18 UTC, melanie-fressard commented on adr/004-open-source-development.md
> +to harness collective expertise for enhanced innovation and trust in the digital
weird format there

2023-10-31 18:18 UTC, melanie-fressard commented on adr/004-open-source-development.md
> +others allows [them] to create meaningful value for [their] customers and engage
weird format here too

2023-10-31 18:18 UTC, melanie-fressard commented on adr/004-open-source-development.md
> +Finally, it's important to understand that "open source" doesn't solely refer to
weird format hereee

2023-10-31 18:18 UTC, melanie-fressard commented on adr/004-open-source-development.md
> +be made available to the public, allowing for community contributions, feedback,
format

2023-10-31 18:47 UTC, melanie-fressard approved these changes

2023-11-01 21:49 UTC, rngadam approved these changes

2023-11-01 21:50 UTC, leejaeka approved these changes

2023-11-01 22:18 UTC, rngadam requested changes
rereading the internal 757/Why-OpenSource-development-at-the-AI-Lab, I see we're missing the whole section "specifics to our situation"  (our existing dependency on open source and publication on alpha, which should at leas tshow up as a reference).

2023-11-02 12:44 UTC, redat97 approved these changes
paradigm , learnt a new word !

2023-11-02 12:57 UTC, CFIALeronB approved these changes

2023-11-02 17:35 UTC, JolanThomassin approved these changes

2023-11-03 21:02 UTC, rngadam commented
@RussellJimmies waiting on you addressing my last review comment

2023-11-07 14:56 UTC, RussellJimmies commented on adr/004-open-source-development.md
> +#### Dependancy to Open Source
That's now tattooed on my brain. 
Corrected.

2023-11-07 16:34 UTC, rngadam approved these changes

2023-11-07 18:31 UTC, merged