Create 002-database-structure.md
ai-cfia/dev-rel-docs pull request #49
Opened 2023-10-16 18:45 UTC by JolanThomassin

2023-10-16 18:48 UTC, JolanThomassin commented
_This comment will be moved in the Pull Request when created_

While it may not be perfect and might be too much focus on the transition when the document need to be focus on the final state, the structure can resemble the following:

# Title:
ADR on our choices of database structure

# Status:
Proposed

# Evaluation Criteria:
We aim to determine the most effective database structure that allows for seamless integration of multiple products, improves flexibility, maintainability, and fosters collaboration among development teams.

# Candidates to Consider:
We have considered various database structure options to accommodate multiple products, including maintaining the existing separate databases and our proposed restructuring approach.

# Research and Analysis of Each Candidate:
In our analysis, we thoroughly examined the existing "louis-db" and "nachet-db" structures and assessed the proposed restructuring. We found that the current isolated databases limited adaptability, while the proposed integrated approach promised improved efficiency and collaboration, similar to transitioning from separate drawers to a spacious wardrobe. The proposed changes would streamline maintenance, reduce errors, and support our growing product variety, making them the preferred choice for our database structure.

# Does/Doesn't Meet Criteria and Why:
The existing separate database approach doesn't meet our criteria as it leads to duplication, lacks flexibility, and hinders collaboration. The proposed changes meet our criteria as they streamline integration, improve maintainability, and enhance code quality.

# Internal Opinions and Feedback:
_Waiting for team members opinion about the proposed changes._

# External Opinions and Feedback:
_Waiting for external opinion about the proposed changes._

# How Did You Evaluate the Candidates?
We evaluated the candidates based on the criteria of efficiency, flexibility, maintainability, and collaborative potential. The proposed changes best align with these criteria.

Why Did You Choose the Winner?
We chose the proposed changes because they align with our objective of creating a single, easy-to-maintain database system that can seamlessly integrate multiple products.

What Is Happening Since Then?
The proposed changes are under consideration for implementation, with a focus on developing the "ailab-db" as the core database and creating a modular product integration system.

Knowing What You Know Now, What Would You Advise People to Do Differently?
We would advise others to consider the long-term benefits of restructuring their database systems to accommodate growth and product diversity, even if it requires initial changes and investments.

Recommendation:
We recommend implementing the proposed changes, including renaming the "louis-db" to "ailab-db" and revising the repository structure for seamless product integration. These changes align with our objective and are vital for efficiently managing databases for multiple products, streamlining deployment and maintenance processes, improving code quality, and facilitating collaboration among development teams.

2023-10-17 12:10 UTC, rngadam requested changes
starting point should be the diagram you created and an explanation of the diagram.

do not use meaningless consulting buzzwords.

2023-10-17 18:54 UTC, rngadam requested changes

2023-10-17 18:54 UTC, rngadam commented on adr/002-database-structure.md
> +![AiLab-db](https://github.com/ai-cfia/dev-rel-docs/assets/98430140/d1795d78-8a13-4c94-86bb-94dd8f824581)
don't use absolute links. these will break if we move things around

2023-10-17 18:54 UTC, rngadam commented on adr/002-database-structure.md
> +- **Candidates to Consider:** We looked at different ways to set up the database for lots of products, like keeping them separate or changing how they're organized.
that's not concrete enough, you need to explain what these alternatives are

2023-10-17 18:54 UTC, rngadam commented on adr/002-database-structure.md
> +In our investigation, we looked very closely at how "louis-db" and "nachet-db" are set up right now, and we also checked out the idea to change things. We found that having separate databases like dr
this document will be given to dba and dbdev, I don't think we want analogies like drawers and wardrobe

2023-10-17 18:54 UTC, rngadam commented on adr/002-database-structure.md
> +In our investigation, we looked very closely at how "louis-db" and "nachet-db" are set up right now, and we also checked out the idea to change things. We found that having separate databases like dr
drop the "we think" from your sentences.

https://hbr.org/2016/10/stop-trying-to-sound-smart-when-youre-writing
https://medium.com/the-brave-writer/stop-using-this-phrase-when-you-write-4dd18c81de49

2023-10-17 18:54 UTC, rngadam commented on adr/002-database-structure.md
> +The way we have separate databases right now isn't good because it causes repetition, is not flexible, and makes it hard for us to work together. But the changes we want to make are better because th
not concrete

2023-10-17 18:54 UTC, rngadam commented on adr/002-database-structure.md
>  - **Internal Opinions and Feedback:** Waiting for team members' opinions about the proposed changes.
don't put solicitation for opinions in the document itself. that's why we have a PR open

2023-10-17 18:54 UTC, rngadam commented on adr/002-database-structure.md
> +We suggest making the changes we talked about, like calling "louis-db" by a new name, "ailab-db," and arranging things in a better way. These changes match our goal and are super important for handli
you can't get more vague than "arranging THINGS in a better WAY"...

2023-10-18 14:37 UTC, JolanThomassin commented on adr/002-database-structure.md
>  - **Internal Opinions and Feedback:** Waiting for team members' opinions about the proposed changes.
Done

2023-10-18 15:08 UTC, JolanThomassin commented on adr/002-database-structure.md
> +![AiLab-db](https://github.com/ai-cfia/dev-rel-docs/assets/98430140/d1795d78-8a13-4c94-86bb-94dd8f824581)
Done

2023-10-18 17:40 UTC, JolanThomassin commented on adr/002-database-structure.md
> +- **Candidates to Consider:** We looked at different ways to set up the database for lots of products, like keeping them separate or changing how they're organized.
Done

2023-10-18 17:45 UTC, JolanThomassin commented on adr/002-database-structure.md
> +In our investigation, we looked very closely at how "louis-db" and "nachet-db" are set up right now, and we also checked out the idea to change things. We found that having separate databases like dr
Done

2023-10-18 17:59 UTC, JolanThomassin commented on adr/002-database-structure.md
> +We suggest making the changes we talked about, like calling "louis-db" by a new name, "ailab-db," and arranging things in a better way. These changes match our goal and are super important for handli
Done

2023-10-18 17:59 UTC, JolanThomassin commented on adr/002-database-structure.md
> +The way we have separate databases right now isn't good because it causes repetition, is not flexible, and makes it hard for us to work together. But the changes we want to make are better because th
I changed it, Done

2023-10-18 23:52 UTC, rngadam commented on adr/002-database-structure.md
> +In our investigation, we looked very closely at how "louis-db" and "nachet-db" are set up right now, and we also checked out the idea to change things. We found that having separate databases like dr
I still see drawers and wardrobe in the latest version.

2023-10-18 23:55 UTC, rngadam commented
@JolanThomassin You've marked comments as Done but when I look at the latest version in Github, it's still not done for many of them. Did you mean to flag this as Draft? Have you pushed your changes?

Feels like you're writing as if you were getting paid by the word:

_"We think it's a good idea "_ 

_"The proposed changes are under consideration for implementation, with a focus"_

_"We picked the changes we suggested because"_

2023-10-19 18:06 UTC, JolanThomassin commented
@rngadam In another PR, I was commenting like this, but you told me to comment "Done," so I misunderstood and thought I was only supposed to write "Done" when it was actually done.

As for the missing fix, this probably happened because I messed something up in the PR system and created two branches. You may have looked at the wrong one. In [this branch](https://github.com/ai-cfia/dev-rel-docs/blob/Issue%2342-Write-an-ADR-on-our-choices-of-database-structure/adr/002-database-structure.md), you can see all the desired changes. You can also find them in the last commits:

![image](https://github.com/ai-cfia/dev-rel-docs/assets/98430140/21fce0ac-5c27-4714-8790-8d96df8da9e3)

2023-10-19 21:33 UTC, rngadam commented
@JolanThomassin peux tu simplifier ton PR et ne pas empiler deux PR une par dessus l'autre pour un ADR? je comprends pas pourquoi faire ça complexe pour un texte.

2023-10-23 19:41 UTC, rngadam commented
I'm being asked to re-review but I don't see significant improvements here.

2023-10-25 14:42 UTC, merged

2023-10-25 14:42 UTC, JolanThomassin commented
Merge because of branch mistake