Issue #46 Write an ADR about choosing Docusaurus to develop the AI-Lab website
ai-cfia/dev-rel-docs pull request #50
Opened 2023-10-17 14:06 UTC by RussellJimmies

#46

2023-10-17 18:44 UTC, rngadam requested changes

2023-10-17 18:44 UTC, rngadam commented on adr/005_why_use_docusaurus.md
> +4. **Docusaurus**: Offers a balanced approach with built-in support for internationalization, is built on the familiar environment of React, and allows for extensive accessibility customizations, mak
there's also Wordpress, which is what the WebServices team was considering....

2023-10-17 18:44 UTC, rngadam commented on adr/005_why_use_docusaurus.md
> +1. **Jekyll**: A robust system, yet it requires multiple plugins for internationalization and has certain limitations in implementing uniform accessibility standards.
missing links to all of these solutions (and also, you haven't linked to Docusaurus main page...)

2023-10-17 18:44 UTC, rngadam commented on adr/005_why_use_docusaurus.md
> +The decision to use Docusaurus will set the stage for the development of a robust, user-centric, and inclusive publishing platform. It will facilitate the swift sharing of knowledge, foster greater c
Missing a references section

2023-10-18 23:25 UTC, rngadam commented
@RussellJimmies I keep getting notified for review requested but I see some of the conversations haven't been addressed yet. Can you convert it to draft until you've addressed the required changes?

2023-10-19 17:44 UTC, RussellJimmies commented on adr/005_why_use_docusaurus.md
> +4. **Docusaurus**: Offers a balanced approach with built-in support for internationalization, is built on the familiar environment of React, and allows for extensive accessibility customizations, mak
Added mention of Wordpress

2023-10-19 17:45 UTC, RussellJimmies commented on adr/005_why_use_docusaurus.md
> +1. **Jekyll**: A robust system, yet it requires multiple plugins for internationalization and has certain limitations in implementing uniform accessibility standards.
Done

2023-10-19 21:27 UTC, rngadam requested changes
fit to the new ADR-001 template

2023-10-20 16:11 UTC, k-allagbe reviewed
Well written.

Just some updates to the 001 template that should be considered.

2023-10-20 16:11 UTC, k-allagbe commented on adr/005_why_use_docusaurus.md
> +
An `Executive Summary` section has been added to the template.

2023-10-20 16:11 UTC, k-allagbe commented on adr/005_why_use_docusaurus.md
> +## Decision
The `Decision` section should be moved above the `Solutions Considered` section.

2023-10-20 17:50 UTC, RussellJimmies commented on adr/005_why_use_docusaurus.md
> +## Decision
Done

2023-10-20 17:50 UTC, RussellJimmies commented on adr/005_why_use_docusaurus.md
> +
Done

2023-10-20 17:50 UTC, RussellJimmies commented on adr/005_why_use_docusaurus.md
> +# ADR 5: Using Docusaurus to develop the AI-Lab website
Done

2023-10-20 18:52 UTC, RussellJimmies commented
Converted to Draft, haven't formatted to linewrap at column 80 yet.

2023-10-23 19:42 UTC, rngadam requested changes
linewrap your paragraphs

2023-10-24 20:54 UTC, rngadam requested changes

2023-10-24 20:54 UTC, rngadam commented on adr/005-choosing-web-development-framework.md
> +* [Government of Canada Digital Standards](https://tinyurl.com/3wz2h7xb)
don't use tinyurl to hide destination

2023-10-25 00:38 UTC, RussellJimmies commented on adr/005-choosing-web-development-framework.md
> +* [Government of Canada Digital Standards](https://tinyurl.com/3wz2h7xb)
I fixed it in the [following commit](https://github.com/ai-cfia/dev-rel-docs/pull/50/commits/b5da6bab9ee091fc63ab1d5a5e1100b280d485fb), plus I used the rewrap extension instead of the fold command.

2023-10-25 18:55 UTC, rngadam approved these changes

2023-10-25 19:03 UTC, redat97 approved these changes
looks great nice job

2023-10-26 13:44 UTC, k-allagbe approved these changes
Looks good to me.

2023-10-30 20:45 UTC, melanie-fressard requested changes
Good job, I like how you write ! There's just a few formatting errors

2023-10-30 20:45 UTC, melanie-fressard commented on adr/005-choosing-web-development-framework.md
> +# ADR 05: Selecting a Web Development Framework for the CFIA AI Lab Website
correct format is # ADR-XXX : Title

2023-10-30 20:45 UTC, melanie-fressard commented on adr/005-choosing-web-development-framework.md
> +### [Jekyll](https://jekyllrb.com/)
should be ### Alternative 1: Jekyll and so on

2023-10-31 13:56 UTC, RussellJimmies commented on adr/005-choosing-web-development-framework.md
> +# ADR 05: Selecting a Web Development Framework for the CFIA AI Lab Website
Done

2023-10-31 14:01 UTC, RussellJimmies commented on adr/005-choosing-web-development-framework.md
> +### [Jekyll](https://jekyllrb.com/)
I just verified ADR-001 and the alternatives are not numbered.

2023-10-31 15:40 UTC, melanie-fressard commented on adr/005-choosing-web-development-framework.md
> +### [Jekyll](https://jekyllrb.com/)
Oh, I probably misunderstood the template since there was Alternative 1 as a title. Nevermind :)

2023-10-31 15:41 UTC, melanie-fressard approved these changes
I would maybe discuss with everyone about the formatting of References, I think ADA7 is a great option. Otherwise no problems for me, good job :)

2023-10-31 15:54 UTC, JolanThomassin approved these changes

2023-11-01 21:42 UTC, rngadam commented
adding @nmeraihi for the final review since the rest of the team approves.

2023-11-02 01:47 UTC, nmeraihi commented on adr/005-choosing-web-development-framework.md
> +
* **Effortless Conversion of Jupyter Notebooks**: Given the data science team's objective to create and share tutorials through Jupyter Notebooks, the ability to easily convert these notebooks to markdown documents with a single click is invaluable. This feature streamlines the process of sharing educational content on our platform, making Docusaurus an even more suitable choice. It's a case of hitting two birds with one stone – we facilitate the easy creation and publication of educational content while adhering to our rapid content publishing goal.
* **Math Equations** : [Mathematical equations](https://docusaurus.io/docs/markdown-features/math-equations) can be rendered using KaTeX.
* **Rich Data Visualization Integration**: Docusaurus supports the embedding of interactive data visualizations (based on ipynb).
* **Extensibility and Plugin Ecosystem**: The extensibility of Docusaurus through its [plugin ecosystem](https://docusaurus.io/docs/advanced/plugins) is a notable advantage
* **Responsive Design**: The responsive design ensures that content, including data visualizations and interactive elements, is accessible and usable across a variety of devices and screen sizes.
* **Search engine optimization (SEO)**:Docusaurus supports [search engine optimization](https://docusaurus.io/docs/seo) in a variety of ways.
* **i18n - Introduction**: [It is easy to translate](https://docusaurus.io/docs/i18n/introduction) a Docusaurus website with its internationalization ([i18n](https://en.wikipedia.org/wiki/Internationalization_and_localization)) support.

2023-11-03 18:15 UTC, RussellJimmies commented on adr/005-choosing-web-development-framework.md
> +
Done

2023-11-03 21:19 UTC, rngadam commented
@nmeraihi don't forget to revisit the conversations and close (after verification of the fix) those that you initiated.

once all is well, approve the PR

2023-11-04 01:44 UTC, nmeraihi approved these changes
excellent! thanks

2023-11-07 14:11 UTC, rngadam commented on adr/005-choosing-web-development-framework.md
> +
@nmeraihi  you have to go back and press "Resolve conversations".

2023-11-07 14:11 UTC, rngadam commented
@RussellJimmies you got everyone's approval 4 days ago, you should be merging.

2023-11-07 16:04 UTC, merged