Fixes #51 : adr for code hosting plateform
ai-cfia/dev-rel-docs pull request #52
Opened 2023-10-17 19:04 UTC by redat97

#51

2023-10-18 12:05 UTC, redat97 commented
Will be using [Microsoft Engineering Playbook's ADR template](https://microsoft.github.io/code-with-engineering-playbook/design/design-reviews/decision-log/doc/adr/0001-record-architecture-decisions/)

2023-10-18 13:59 UTC, rngadam commented
@redat97 

> Will be using [Microsoft Engineering Playbook's ADR template](https://microsoft.github.io/code-with-engineering-playbook/design/design-reviews/decision-log/doc/adr/0001-record-architecture-decisions/)

you should be using our own guide:

https://github.com/ai-cfia/dev-rel-docs/pull/44/files

2023-10-18 14:26 UTC, redat97 commented
https://github.com/ai-cfia/dev-rel-docs/pull/52#issuecomment-1768525065
@rngadam I think we should have an empty template like the one I linked, unless you disagree I will create an issue for that and I will link it to this PR

2023-10-18 23:21 UTC, rngadam commented
@redat97 english spelling of platform is platform, not plateform (as per title)

2023-10-20 21:53 UTC, melanie-fressard commented on adr/007-code-hosting-platform.md
> +A choice needed to be made to be able to manage and share code. It needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
I think you forgot to format your file, you can use the extension Guy provided.

2023-10-20 21:53 UTC, melanie-fressard commented on adr/007-code-hosting-platform.md
> +* **Community and Open-Source Focus**
As Guy mentioned in my PR, we should limit formatting in the ADRs, bolding is not necessary

2023-10-20 23:07 UTC, k-allagbe reviewed
Looks good to me otherwise.

2023-10-23 12:29 UTC, rngadam requested changes

2023-10-23 12:29 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +- Allows efficient build, commit, and deployment of code.
the pros you list are not specific to Azure DevOps.

2023-10-23 12:29 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +- Seamless management of repositories, branches, and pull requests.
idem

2023-10-23 12:29 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +A choice needed to be made to be able to manage and share code. It needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
the agency does not take an opensource approach (yet), the AI Lab does as directed by the treasury board here:

https://www.canada.ca/en/government/system/digital-government/government-canada-digital-standards.html

2023-10-23 12:29 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +    * GitHub’s interface and workflow are considered intuitive, especially for open-source developers.
that's too subjective. any numbers?

2023-10-23 12:35 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +A choice needed to be made to be able to manage and share code. It needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
the fact that the repositories are public is not considered open source?

2023-10-24 13:39 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +* **Community and Open-Source Focus**
changed thanks

2023-10-24 13:39 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +A choice needed to be made to be able to manage and share code. It needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
true thanks !

2023-10-24 13:40 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +- Allows efficient build, commit, and deployment of code.
I went a little more in depth for each ones and more specific lmk what you think

2023-10-24 13:40 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +- Seamless management of repositories, branches, and pull requests.
https://github.com/ai-cfia/dev-rel-docs/pull/52#discussion_r1370173678

2023-10-24 13:41 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +A choice needed to be made to be able to manage and share code. It needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
right changed to AI lab and added the meaning of the acronym for the first use

2023-10-24 13:47 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +    * GitHub’s interface and workflow are considered intuitive, especially for open-source developers.
it was really a general feeling from most reviews I added the extra pros you asked me to add and gave a bit more context on why/how I came to theses conclusions

2023-10-24 14:19 UTC, melanie-fressard requested changes
Needs a few corrections but otherwise it looks good to me, great work :)

2023-10-24 14:19 UTC, melanie-fressard commented on adr/007-code-hosting-platform.md
> +# ADR 7 : Selecting GitHub as Code Hosting Platform
Change the title to ADR-007 : Selecting GitHub as Code Hosting Platform

2023-10-24 14:19 UTC, melanie-fressard commented on adr/007-code-hosting-platform.md
> +This ADR documents the decision to select GitHub as the primary platform for hosting, managing, and sharing code within our agency's AI (Artificial Intelligence) lab.
would put "sharing code within our agency's Artificial Intelligence Laboratory (AI Lab).

2023-10-24 14:19 UTC, melanie-fressard commented on adr/007-code-hosting-platform.md
> +A choice needed to be made to be able to manage and share code. It needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
you need to wrap the text at column 80

2023-10-24 14:19 UTC, melanie-fressard commented on adr/007-code-hosting-platform.md
> +In light of the open source mindset of the AI Lab, GitHub clearly stood out from the rest of the options available for a couple reasons :
...stood out from the rest of the available options

2023-10-24 14:19 UTC, melanie-fressard commented on adr/007-code-hosting-platform.md
> +    * $150k in approximate cost savings per year
missing dots at the end of your sentences

2023-10-24 14:19 UTC, melanie-fressard commented on adr/007-code-hosting-platform.md
> +    * The platform’s extensive user base includes 4 million organizations, and 330 million repositories, with adoption by 90% of Fortune 100 companies.
explain what fortune 100 is maybe

2023-10-24 14:19 UTC, melanie-fressard commented on adr/007-code-hosting-platform.md
> +The decision to use GitHub will help the agency's reach; it will get more people to look at the products and support the open source goals. It will also make DevOps a lot easier with its large commun
I would remove the ; and just put a ,

2023-10-24 20:40 UTC, rngadam requested changes

2023-10-24 20:40 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +* Integraded AI software.
typo

2023-10-24 20:40 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +The decision to use GitHub will help the agency's reach, it will get more people to look at the products and support the open source goals. It will also make DevOps a lot easier with its large commun
"the agency"? two computer science teams? 

There's an AI lab with a software development team and a data science team.

2023-10-24 20:40 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +* Iron Mountain plateform with GitLab ultimate :
platform typo again

2023-10-24 20:40 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +    * GitHub’s continued innovation helped the plateform to stay relevant for many years (created in 2008).
platform typo

2023-10-24 20:40 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +* Alignment with Microsoft:
you'd have to explain why we care that it aligns with Microsoft 

https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/cloud-services/cloud-adoption-strategy-2023-update.html

2023-10-25 16:27 UTC, k-allagbe approved these changes

2023-10-25 16:27 UTC, k-allagbe commented on adr/007-code-hosting-platform.md
> +This ADR documents the decision to select GitHub as the primary platform for hosting, managing, and sharing code within the CFIA's (Canadian Food Inspection Agency) AI (Artificial Intelligence) Lab.
I would suggest `AI Lab (Artificial Intelligence Laboratory)`.

2023-10-25 19:10 UTC, rngadam requested changes

2023-10-25 19:10 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +* Iron Mountain platform with GitLab ultimate :
who's Iron Mountain and why do we care?

I think you're reporting an example here, but you should be clear and turn it into a paragraph

2023-10-25 19:10 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +The decision to use GitHub will help the CFIA's AI Lab reach, it will get more people to look at the products and support the open source goals. It will also make DevOps a lot easier with its large c
Stop using It to start your sentences. but the actual what "it" is.

 It will also -> Github will also 
 
 or use synonyms that expand on what "it" is: This code sharing platform will also...

2023-10-30 20:17 UTC, rngadam requested changes

2023-10-30 20:17 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +[GetApp * GitLab Reviews](https://www.getapp.com/it-management-software/a/gitlab/reviews/#:~:text=Pros.%20Its%20intuitive%20interface%20and%20robust%20feature%20set,challenging%20for%20new%20users%20
remove the text highlight after the hashmark # (it's an optional part of the URL)

2023-10-30 20:17 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +A choice needed to be made to be able to manage and share code. It needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
you added "Government of Canada Digital Standard" but didn't provide the source in your references

and it's "Government of Canada Digital Standards" (s)

2023-10-30 20:22 UTC, RussellJimmies commented on adr/007-code-hosting-platform.md
> +## Decision
Would it be pertinent to mention GitHub Pages? A great functionality which allows us to deploy resources for free, like Nachet-Frontend or even the Docusaurus website?

2023-10-30 20:27 UTC, melanie-fressard reviewed
Great job, you just need to format your file :)

2023-10-30 20:27 UTC, melanie-fressard commented on adr/007-code-hosting-platform.md
> +The team needs a platform to be able to manage and share code which needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
I think it's still needs to be wrapped

2023-10-30 21:12 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +## Decision
yes, amazing feature

2023-11-01 10:10 UTC, redat97 commented
Closed this by accident when I tried to rename the branch

2023-11-01 21:56 UTC, rngadam requested changes
Need to go back and address the previous conversations and link your references to where they are used in text (following @RussellJimmies method in his own ADR)

2023-11-01 21:56 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +The team needs a platform to be able to manage and share code which needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
s/needs to/should/

2023-11-01 21:56 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +    * Because GitHub is owned by Microsoft, which will help the lab stay in line with the Cloud First policy requirement of the Government of Canada. This makes sure that the contracts and operations
Because GitHub is owned by Microsoft, a key supplier of cloud infrastructure for the Government of Canada (GoC), this choice will help keep the lab in line with the Cloud First policy requirement of the Government of Canada.

2023-11-02 17:52 UTC, JolanThomassin commented on adr/007-code-hosting-platform.md
> +## Consequences
I feel like it's missing a little part explaining the cons of GitHub, even if there is a small part, I feel weird not to have one.

2023-11-02 17:52 UTC, JolanThomassin approved these changes

2023-11-07 20:06 UTC, melanie-fressard approved these changes
Good job :)

2023-11-08 15:10 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +    * Because GitHub is owned by Microsoft, which will help the lab stay in line with the Cloud First policy requirement of the Government of Canada. This makes sure that the contracts and operations
You reply done but I don't see the updates

2023-11-08 15:11 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +## Consequences
I agree - I think you should have made this a "Request changes" too.

2023-11-08 15:13 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +The team needs a platform to be able to manage and share code which needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
I don't see the correction

2023-11-08 15:29 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +The team needs a platform to be able to manage and share code which needed to be an online platform so that team members could work together in real time from anywhere in the country as well as allow
don't know what happened I remember making the change and google what s/ meant but changed now

2023-11-08 15:30 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +    * Because GitHub is owned by Microsoft, which will help the lab stay in line with the Cloud First policy requirement of the Government of Canada. This makes sure that the contracts and operations
updated

2023-11-09 13:35 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +## Consequences
@redat97 address this comment

2023-11-09 13:35 UTC, rngadam requested changes
see comment from @JolanThomassin

2023-11-12 18:06 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +## Consequences
I added two but I got to be honest this review sums it up pretty good
![Screenshot_48](https://github.com/ai-cfia/dev-rel-docs/assets/9827730/32266ab7-ad4b-42fc-be7a-fed5ae82ecd0)

2023-11-14 14:15 UTC, CFIALeronB approved these changes

2023-11-15 14:07 UTC, rngadam commented
Get approval from @ThomasCardin first

2023-11-17 14:55 UTC, ThomasCardin commented on adr/007-code-hosting-platform.md
> +* Self-hostable, providing greater control over data and customization.
I added this. Is it okay with you @redat97 @rngadam. Here is the "cons" for this "pros" [79](https://github.com/ai-cfia/dev-rel-docs/blob/redat97/issue51/adr/007-code-hosting-platform.md?plain=1#L79)

2023-11-17 15:27 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +* Self-hostable, providing greater control over data and customization.
yes forsure it's collaborative work you can add whatever you think should be added

2023-11-20 11:56 UTC, rngadam requested changes
This document is not formatted to wrap at column 80. This should be caught in a status check?

2023-11-20 18:42 UTC, redat97 commented
> This document is not formatted to wrap at column 80. This should be caught in a status check?

how do you configure that exactly? I followed the wiki

2023-11-20 18:45 UTC, redat97 commented
@melanie-fressard showed me an extension nvm

2023-11-21 21:06 UTC, rngadam requested changes

2023-11-24 13:40 UTC, ThomasCardin approved these changes
LGTM!

2023-11-27 17:49 UTC, redat97 commented on adr/007-code-hosting-platform.md
> +* Mainly suited for developers.
I think what I meant to say was it's mainly aimed at a team of multiple developers, in the sense that it's for bigger project which require more ressources than something like github. Keep in mind I never used it this was a feeling from what I got looking on the internet so I hope it's not false or wrong

2023-11-27 21:45 UTC, rngadam requested changes

2023-11-27 21:45 UTC, rngadam commented on adr/007-code-hosting-platform.md
> +* Mainly suited for developers.
I don't see it, I think we should just remove this bullet point

2023-11-28 16:57 UTC, rngadam commented
> I can see it in my last commit, weird but this was the point
> Mainly suited for a team of developers which work on larger project requiring more ressources opposed to GitHub.
> @rngadam this was the point, remove or keep?

I don't see it as I don't agree with the assessment, seems rather arbitrary.

remove it.

2023-11-28 17:56 UTC, rngadam commented
> This document is not formatted to wrap at column 80. This should be caught in a status check?

still not fixed

2023-11-29 16:37 UTC, rngadam approved these changes

2023-11-30 11:50 UTC, rngadam requested changes
@redat97 rebase and squash to clean up the commit history.

2023-11-30 16:39 UTC, redat97 commented
No idea why it was closed I ran a command from vs code and closed it but all tests are passing now

2023-11-30 21:15 UTC, redat97 commented on adr/001-ailab-using-adr.en-ca.md
> +=======
removed

2023-11-30 21:21 UTC, redat97 commented
Had to remove some links that died

2023-12-01 00:29 UTC, redat97 commented on adr/001-ailab-using-adr.en-ca.md
> +=======
fixed

2023-12-01 18:30 UTC, redat97 commented on README.md
> +<<<<<<< HEAD
done

2023-12-05 11:38 UTC, rngadam requested changes

2023-12-05 11:38 UTC, rngadam commented on adr/index.md
>  * [ADR-005: Selecting a Web Development Framework for the AI Lab
index.md is missing links to ADR 3,4,6 (apparently never added)

2023-12-05 11:38 UTC, rngadam commented on adr/index.md
> +Website](./005-choosing-web-development-framework.md) - Why we decided to
can you think if the link works without ./ 

https://github.blog/2013-01-31-relative-links-in-markup-files/

2023-12-05 13:16 UTC, redat97 commented on adr/index.md
> +Website](./005-choosing-web-development-framework.md) - Why we decided to
changed

2023-12-05 13:18 UTC, redat97 commented
docker link is returning 404 for some reason but works when I go on it I tried with deadlinkchecker.com as well and same thing

2023-12-06 12:05 UTC, rngadam requested changes
rebase and rework the history so we don't the extra commits to introduce and then fix bad merges

2023-12-06 12:05 UTC, rngadam commented on adr/index.md
>  * [ADR-005: Selecting a Web Development Framework for the AI Lab
> do I still reference this specific issue when making global changes like this?

no; referencing an unrelated issue would just make the commit more confusing.

2023-12-12 09:52 UTC, rngadam approved these changes

2023-12-12 11:28 UTC, merged