Issue #48 -  Write an ADR on our choices of database server
ai-cfia/dev-rel-docs pull request #53
Opened 2023-10-17 20:00 UTC by melanie-fressard

Fixes #48

2023-10-18 06:48 UTC, rngadam requested changes

2023-10-18 06:48 UTC, rngadam commented on adr/003-database-choice.md
> +*This ADR details our thought process regarding a database system's choice and highlights the factors influencing this choice. We considerd both MySQL and PostgreSQL, ultimately opting for PostgreSQL
typo considered.

nowhere in this document is that comparison done between MySQL and PostgreSQL. Although MySQL is indeed used (through Wordpress), the real competitor at the CFIA internally is proprietary databases such as Microsoft SQL Server.

2023-10-18 06:48 UTC, rngadam commented on adr/003-database-choice.md
> +Today, effective data management is crucial to CFIA as we manage enormous amounts of information, requiring a database management system (DBMS). This choice is vital to ensure the security of sensiti
we're not deciding for the CFIA but the CFIA AI Lab.

2023-10-18 06:48 UTC, rngadam commented on adr/003-database-choice.md
> +- **Indexing:** Wide array of indexing methods, enhancing the efficiency of data queries and application performance.
None of the above 3 items are specific avantages to PostgreSQL

2023-10-18 06:48 UTC, rngadam commented on adr/003-database-choice.md
> +- **Reliability:** Renowned for its reliability and stability.
sources?

2023-10-18 06:48 UTC, rngadam commented on adr/003-database-choice.md
> +- [Postgres pgvector Extension - Vector Database with PostgreSQL / Langchain Integration](https://youtu.be/FDBnyJu_Ndg?si=sBfBluS3G2TlW6RN) - BugBytes
reference the vector extension but nowhere in the document is it explained how it is used; this should actually be key to the choice as the diversity of data type is useful specifically for our AI applications.

2023-10-18 06:48 UTC, rngadam commented on adr/003-database-choice.md
> +We decided to adopt PostgreSQL as our DBMS for its scalability, the strength of its open-source community, and its reliable data integrity.
should be more detailed on the feature set we use with the database

2023-10-18 13:29 UTC, melanie-fressard commented on adr/003-database-choice.md
> +Today, effective data management is crucial to CFIA as we manage enormous amounts of information, requiring a database management system (DBMS). This choice is vital to ensure the security of sensiti
true, I'm changing this

2023-10-18 14:17 UTC, melanie-fressard commented on adr/003-database-choice.md
> +*This ADR details our thought process regarding a database system's choice and highlights the factors influencing this choice. We considerd both MySQL and PostgreSQL, ultimately opting for PostgreSQL
I indeed forgot MySQL here, instead of errasing it, I also added Microsoft SQL Sever and did a comparison on each of them in solutions considered.

2023-10-18 14:18 UTC, melanie-fressard commented on adr/003-database-choice.md
> +- **Indexing:** Wide array of indexing methods, enhancing the efficiency of data queries and application performance.
I deleted it

2023-10-18 15:31 UTC, melanie-fressard commented on adr/003-database-choice.md
> +We decided to adopt PostgreSQL as our DBMS for its scalability, the strength of its open-source community, and its reliable data integrity.
done

2023-10-19 00:06 UTC, rngadam requested changes

2023-10-19 13:30 UTC, melanie-fressard commented on adr/003-database-choice.md
> +*This ADR details our thought process regarding a database system's choice and highlights the factors influencing this choice. We considerd MySQL, Microsoft SQL Server, and PostgreSQL, ultimately opt
was it the "'s" ? not sure to understand

2023-10-19 13:34 UTC, melanie-fressard commented on adr/003-database-choice.md
> +*This ADR details our thought process regarding a database system's choice and highlights the factors influencing this choice. We considerd MySQL, Microsoft SQL Server, and PostgreSQL, ultimately opt
i'm stupid, sorry it's corrected

2023-10-19 13:47 UTC, RussellJimmies commented on adr/003-database-choice.md
> +Today, effective data management is crucial to CFIA's AI Lab as we manage enormous amounts of information, requiring a database management system (DBMS). This choice is vital to ensure the security o
[...] support data analysis, *MISSING A SPACE* facilitate collaboration [...]

2023-10-19 13:52 UTC, RussellJimmies commented on adr/003-database-choice.md
> +We decided to adopt PostgreSQL as our database management system (DBMS) due to its open-source nature and the presence of a large and active community. This guarantees regular updates, bug fixes, and
[...] which is what the AI Lab **does**

2023-10-19 13:55 UTC, RussellJimmies commented on adr/003-database-choice.md
> +- **Open Source and Community Support:** Open-source nature and big community ensure regular updates, bug fixes, and a lot of extensions and plugins.
No hyphen (-) in "open source".

2023-10-19 14:02 UTC, melanie-fressard commented on adr/003-database-choice.md
> +Today, effective data management is crucial to CFIA's AI Lab as we manage enormous amounts of information, requiring a database management system (DBMS). This choice is vital to ensure the security o
done

2023-10-19 14:02 UTC, melanie-fressard commented on adr/003-database-choice.md
> +We decided to adopt PostgreSQL as our database management system (DBMS) due to its open-source nature and the presence of a large and active community. This guarantees regular updates, bug fixes, and
done

2023-10-19 14:04 UTC, melanie-fressard commented on adr/003-database-choice.md
> +- **Open Source and Community Support:** Open-source nature and big community ensure regular updates, bug fixes, and a lot of extensions and plugins.
"Hyphenate open-source as an adjective preceding a noun. Don't hyphenate in other instances."

2023-10-19 14:10 UTC, redat97 reviewed
looks great to me

2023-10-19 19:01 UTC, rngadam requested changes

2023-10-19 19:04 UTC, rngadam commented on adr/003-database-choice.md
> +- **Reliability:** Highly reliable and has a proven track record for handling mission-critical and high-traffic applications. It supports ACID (Atomicity, Consistency, Isolation, Durability) properti
look at whitepapers from commercial support companies of postgresql

2023-10-19 21:38 UTC, rngadam requested changes

2023-10-19 21:38 UTC, rngadam commented on adr/003-database-choice.md
> +Today, effective data management is crucial to CFIA's AI Lab as we manage
Spell out your acronyms the first time you use them, even for CFIA and AI

2023-10-19 21:38 UTC, rngadam commented on adr/003-database-choice.md
> +database!](https://www.enterprisedb.com/postgres-tutorials/why-more-and-more-enterprises-are-choosing-postgresql-their-go-database#:~:text=take%20another%20look.-,PostgreSQL%20is%20reliable,the%20tra
clean up your URL (remove after the #)

2023-10-20 13:22 UTC, melanie-fressard commented on adr/003-database-choice.md
> +Today, effective data management is crucial to CFIA's AI Lab as we manage
done

2023-10-20 13:22 UTC, melanie-fressard commented on adr/003-database-choice.md
> +- **Reliability:** Highly reliable and has a proven track record for handling mission-critical and high-traffic applications. It supports ACID (Atomicity, Consistency, Isolation, Durability) properti
currently working on this :)

2023-10-20 16:35 UTC, k-allagbe reviewed
Well written.

Just consider using less formatting to keep the ADRs simple.

2023-10-20 16:35 UTC, k-allagbe commented on adr/003-database-choice.md
> +- **Open Source and Community Support:** Open source nature and big community
We should limit formatting in the ADRs. Bolding should not be necessary.

2023-10-20 21:47 UTC, melanie-fressard commented on adr/003-database-choice.md
> +- **Open Source and Community Support:** Open source nature and big community
done

2023-10-20 21:48 UTC, melanie-fressard commented on adr/003-database-choice.md
> +- **Reliability:** Highly reliable and has a proven track record for handling mission-critical and high-traffic applications. It supports ACID (Atomicity, Consistency, Isolation, Durability) properti
i added some examples, would you like more ?

2023-10-20 21:55 UTC, melanie-fressard commented on adr/003-database-choice.md
> +- **Open Source and Community Support:** Open-source nature and big community ensure regular updates, bug fixes, and a lot of extensions and plugins.
done

2023-10-23 15:39 UTC, redat97 approved these changes

2023-10-23 20:27 UTC, melanie-fressard commented on adr/003-database-choice.md
> +- Thom Brown
done, as discussed I'll use the Rewrap extension for now

2023-10-23 20:27 UTC, melanie-fressard commented on adr/003-database-choice.md
> +(CFIA) Artificial Intelligence (AI) Lab as we manage enormous amounts of
thanks, that's much better ! done

2023-10-23 21:02 UTC, rngadam approved these changes
I like it. The example with Microsoft diagnostic metrics is particularly compelling (given that they also make SQL Server). 

Get review comments from the whole team, including @nmeraihi

2023-10-23 21:19 UTC, k-allagbe approved these changes
Neat.

2023-10-23 21:41 UTC, RussellJimmies approved these changes

2023-10-23 21:53 UTC, leejaeka approved these changes

2023-10-24 13:09 UTC, JolanThomassin commented on adr/003-database-choice.md
> +# ADR 3: Adopting PostgreSQL as the Database System
I don't know if we need to call it ADR 003 or ADR 3

2023-10-24 13:49 UTC, redat97 commented on adr/003-database-choice.md
> +# ADR 3: Adopting PostgreSQL as the Database System
if i'm not mistaken, the file name needs to be 00X but not the title

2023-10-24 13:57 UTC, k-allagbe commented on adr/003-database-choice.md
> +# ADR 3: Adopting PostgreSQL as the Database System
File name: XXX-tag
Title: ADR-XXX: title
It was suggested yesterday by @JolanThomassin and approved by @rngadam.

2023-10-24 14:07 UTC, redat97 commented on adr/003-database-choice.md
> +# ADR 3: Adopting PostgreSQL as the Database System
cool cool my bad

2023-10-24 14:08 UTC, melanie-fressard commented on adr/003-database-choice.md
> +# ADR 3: Adopting PostgreSQL as the Database System
done, could you provide a link to this discussion maybe ?

2023-10-24 14:18 UTC, k-allagbe commented on adr/003-database-choice.md
> +# ADR 3: Adopting PostgreSQL as the Database System
https://github.com/ai-cfia/dev-rel-docs/pull/44#discussion_r1368999714

2023-10-24 14:19 UTC, melanie-fressard commented on adr/003-database-choice.md
> +# ADR 3: Adopting PostgreSQL as the Database System
Perfect, thanks !

2023-10-24 15:17 UTC, redat97 approved these changes

2023-10-24 16:55 UTC, nmeraihi approved these changes

2023-10-24 20:44 UTC, rngadam requested changes

2023-10-24 20:44 UTC, rngadam commented on adr/003-database-choice.md
> +This ADR details our thought process regarding our database system's choice and
ADR is also an acronym you should spell out the first time you use it.

2023-10-24 20:44 UTC, rngadam commented on adr/003-database-choice.md
> +We decided to adopt PostgreSQL as our DBMS due to its open source nature and the
who's we

2023-10-25 13:51 UTC, melanie-fressard commented on adr/003-database-choice.md
> +This ADR details our thought process regarding our database system's choice and
done, also done on my 2nd ADR

2023-10-25 13:51 UTC, melanie-fressard commented on adr/003-database-choice.md
> +We decided to adopt PostgreSQL as our DBMS due to its open source nature and the
changed to AI Lab

2023-10-25 19:03 UTC, rngadam approved these changes

2023-11-02 17:19 UTC, leejaeka approved these changes

2023-11-06 23:04 UTC, merged