Issue #43 - Write an ADR on our choices of database change management
ai-cfia/dev-rel-docs pull request #54
Opened 2023-10-17 20:23 UTC by melanie-fressard

Fixes #43

2023-10-18 06:49 UTC, rngadam requested changes

2023-10-18 06:49 UTC, rngadam commented on adr/006-database-change-management.md
> +# ADR 3: How we manage changes in databases
ADR 3 in title but this is in a file for ADR 6

2023-10-18 13:20 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +# ADR 3: How we manage changes in databases
you're right I forgot to change it

2023-10-19 00:10 UTC, rngadam requested changes

2023-10-19 00:10 UTC, rngadam commented on adr/006-database-change-management.md
> +*Our solution is to incorporate semantic versioning information into schema names to maintain version control as well as to clone the current schema to migrate and transform data in a new schema impl
typo management

2023-10-19 00:10 UTC, rngadam commented on adr/006-database-change-management.md
> +1. **Manual SQL Scripts**:
don't manually number bullet points in list.

1. did
1. you
1. know
1. just
1. putting 
1. `1.` repeatedly
1. in a list
1. auto-numbers?

2023-10-19 13:36 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +*Our solution is to incorporate semantic versioning information into schema names to maintain version control as well as to clone the current schema to migrate and transform data in a new schema impl
done

2023-10-19 13:37 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +1. **Manual SQL Scripts**:
so I just put 1 everywhere ?

2023-10-19 14:07 UTC, RussellJimmies commented on adr/006-database-change-management.md
> +Our solution is to incorporate semantic versioning information into schema names to maintain version control as well as to clone the current schema to migrate and transform data in a new schema imple
[...] **implementing** changes. 

[...] good **change** management

2023-10-19 14:09 UTC, RussellJimmies commented on adr/006-database-change-management.md
> +* verify changes are correctly applied by running a test suite (probably backend test suite as it relates to the database).
**V**erify

2023-10-19 14:09 UTC, RussellJimmies commented on adr/006-database-change-management.md
> +* revert changes if necessary (or switch back to an older version of the database).
**R**evert

2023-10-19 14:17 UTC, RussellJimmies commented on adr/006-database-change-management.md
> +   - *Pros*: Infra-as-Code (IaC) principles, easy integration with DevOps practices, consistent versioning.
Infrastructure-as-Code

2023-10-19 15:04 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +* revert changes if necessary (or switch back to an older version of the database).
done

2023-10-19 15:04 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +* verify changes are correctly applied by running a test suite (probably backend test suite as it relates to the database).
done

2023-10-19 19:55 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +1. **Manual SQL Scripts**:
as discussed, bullet points are better

2023-10-19 21:40 UTC, rngadam requested changes

2023-10-19 21:40 UTC, rngadam commented on adr/006-database-change-management.md
> +- Incorporate semantic versioning information into schema names to maintain
explain semantic versioning somwhere

provide a concrete example of the workflow for database changes (with diagram)

2023-10-20 16:49 UTC, k-allagbe reviewed
Well written.

2023-10-20 16:49 UTC, k-allagbe commented on adr/006-database-change-management.md
> +and highlights the factors influencing this choice. We considerd a few solutions
typo: missing an e

2023-10-23 15:37 UTC, redat97 approved these changes
looks great good job

2023-10-23 20:45 UTC, rngadam requested changes

2023-10-24 14:06 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +- Incorporate semantic versioning information into schema names to maintain
I explained semantic versionning but I'm not sure about the diagram, what do we need exactly ?

2023-10-24 18:48 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +- Incorporate semantic versioning information into schema names to maintain
I tried to explain as we dicussed

2023-10-24 19:42 UTC, k-allagbe approved these changes
Looks good to me otherwise.

2023-10-24 19:42 UTC, k-allagbe commented on adr/006-database-change-management.md
> +#### Cons*:
`*` character probably an omition? Present below as well.

2023-10-24 19:42 UTC, k-allagbe commented on adr/006-database-change-management.md
> +  louis_x.x.x - a MAJOR release would break the database, it includes modifiying
typo in `modifiying`.

2023-10-24 19:42 UTC, k-allagbe commented on adr/006-database-change-management.md
> +To address the context and requirements, the following approach is proposed:
I suggest `we adopted the following approach`. Because at that point we have already chosen the approach.

2023-10-24 20:57 UTC, rngadam approved these changes

2023-10-25 13:44 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +  louis_x.x.x - a MAJOR release would break the database, it includes modifiying
done

2023-10-25 13:44 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +#### Cons*:
done

2023-10-25 13:46 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +To address the context and requirements, the following approach is proposed:
Corrected in " the following approach is adopted:"

2023-10-25 19:00 UTC, rngadam commented on adr/006-database-change-management.md
> +CFIA projects Finesse and Louis Chat depend heavily on the PostgreSQL database.
products

2023-10-25 19:00 UTC, rngadam commented on adr/006-database-change-management.md
> +CFIA projects Finesse and Louis Chat depend heavily on the PostgreSQL database.
CFIA AI Lab new products such as Finesse and Louis rely heavily on the PostgreSQL database.

2023-10-25 19:01 UTC, rngadam commented on adr/006-database-change-management.md
> +several considerations and challenges:
when listing negatives, you also list to provide mitigation measures to reduce the impact.

2023-10-25 20:25 UTC, rngadam requested changes

2023-10-25 20:25 UTC, rngadam commented on adr/006-database-change-management.md
> +  noticed.
be noticeable to users of the database.

2023-10-25 22:11 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +This Architecture Decision Record (ADR) details our thought process regarding our database management system
done

2023-10-25 22:11 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +CFIA projects Finesse and Louis Chat depend heavily on the PostgreSQL database.
done

2023-10-25 22:17 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +several considerations and challenges:
thank you, i added this

2023-10-25 22:17 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +  noticed.
done

2023-10-30 14:54 UTC, rngadam commented on adr/006-database-change-management.md
> +# ADR 3: How we manage changes in databases
new format (see updated ADR-001) is ADR-003

2023-10-30 15:01 UTC, rngadam requested changes

2023-10-30 15:21 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +  tables for example. PATCH is just minor modifications that shouldn't be be
done

2023-10-30 15:21 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +  members understand and follow the conventions consistently.
done

2023-10-30 20:32 UTC, RussellJimmies approved these changes

2023-10-30 21:14 UTC, rngadam approved these changes

2023-10-31 13:15 UTC, JolanThomassin approved these changes

2023-11-01 17:35 UTC, leejaeka approved these changes

2023-11-02 01:15 UTC, nmeraihi commented on adr/006-database-change-management.md
> +* Revert changes if necessary (or switch back to an older version of the
should we clarify how?  strategy on how rollbacks would be handled?

2023-11-02 01:18 UTC, nmeraihi commented on adr/006-database-change-management.md
General comment is to specify how the chosen solution aligns with BIS team, all good for our current usage. Let's make sure that folks aligns with this ADR. Excellent work @melanie-fressard  and team!

2023-11-02 19:57 UTC, melanie-fressard commented on adr/006-database-change-management.md
> +* Revert changes if necessary (or switch back to an older version of the
done

2023-11-03 00:59 UTC, nmeraihi approved these changes

2023-11-03 21:12 UTC, rngadam commented on adr/006-database-change-management.md
I'm also curious about how the BIS team manages schema changes - follow up into an internal board task.

2023-11-03 21:12 UTC, rngadam approved these changes

2023-11-06 14:58 UTC, merged