Issue#42 Write an ADR on our choices of database structure #49
ai-cfia/dev-rel-docs pull request #57
Opened 2023-10-25 14:43 UTC by JolanThomassin

2023-10-25 14:45 UTC, JolanThomassin commented
Now this is related to the main 👍

2023-10-25 19:07 UTC, rngadam requested changes

2023-10-25 19:07 UTC, rngadam commented on adr/002-database-structure.md
> +We have decided to transition to a Consolidated Database Approach for AiLab-db. This decision is rooted in our evaluation criteria, which emphasize flexibility, maintainability, efficiency, and colla
you supposed decided to write ailab-db AiLab-db. be consistent and use the lowercase name

2023-10-25 19:07 UTC, rngadam commented on adr/002-database-structure.md
> +This ADR discusses our choices for the ailab-db database structure. We want to encourage collaboration between various teams and products while increasing flexibility and ease of maintenance.
We want to encourage data sharing between software products produced by the CFIA AI Lab while increasing flexibility and ease of maintenance by consolidating our product databases under a single database server.

2023-10-25 19:49 UTC, JolanThomassin commented on adr/002-database-structure.md
> +We have decided to transition to a Consolidated Database Approach for AiLab-db. This decision is rooted in our evaluation criteria, which emphasize flexibility, maintainability, efficiency, and colla
The last Ailab-db has been found and fixed; now all Ailab-db entries are being written correctly. [8ce9ca3](https://github.com/ai-cfia/dev-rel-docs/pull/57/commits/8ce9ca30dca7be4581f889c58a878853e9c6bfd1)

2023-10-25 19:49 UTC, JolanThomassin commented on adr/002-database-structure.md
> +This ADR discusses our choices for the ailab-db database structure. We want to encourage collaboration between various teams and products while increasing flexibility and ease of maintenance.
I changed the text a little so it's more clear and it follow the text you give me in this comment. [a14acb8](https://github.com/ai-cfia/dev-rel-docs/pull/57/commits/a14acb86abec7bf8524cc9f97ba7f1215ae981c5)

2023-11-08 16:08 UTC, melanie-fressard requested changes
great job, I think it needs some changes but it should be good once it's done imo

2023-11-08 16:08 UTC, melanie-fressard commented on adr/002-database-structure.md
> +## Optional Illustration
Maybe change optional illustration to an actual title for your diagram

2023-11-08 16:08 UTC, melanie-fressard commented on adr/002-database-structure.md
> +This ADR describes our plan to promote sharing data between software products created by the CFIA AI Lab. At the same time, we aim to make things more flexible and easier to maintain by bringing all
you need to say what CFIA and AI Lab stand for before using the acronyms

2023-11-08 16:08 UTC, melanie-fressard commented on adr/002-database-structure.md
> +This ADR describes our plan to promote sharing data between software products created by the CFIA AI Lab. At the same time, we aim to make things more flexible and easier to maintain by bringing all
adr too

2023-11-08 16:08 UTC, melanie-fressard commented on adr/002-database-structure.md
> +Our previous ailab-db architecture required maintenance of several databases, notably "louis-db" and "nachet-db." Although this approach initially provides clarity, it ultimately results in redundanc
you need to wrap your text at column 80 with the extension Rewrap

2023-11-08 16:08 UTC, melanie-fressard commented on adr/002-database-structure.md
> +We have decided to transition to a Consolidated Database Approach for ailab-db. This decision is rooted in our evaluation criteria, which emphasize flexibility, maintainability, efficiency, and colla
Maybe explain a bit more what is Consolidated Database Approach

2023-11-08 16:08 UTC, melanie-fressard commented on adr/002-database-structure.md
> +### Positive Consequences:
don't separate both, you should present negative aspects here but nuance it with positive ones

2023-11-08 16:08 UTC, melanie-fressard commented on adr/002-database-structure.md
> +- Adapting to the new structure may temporarily complicate the development process.
you don't have the reference section, I don't think you need one but it should be here anyway in my opinion

2023-11-08 20:00 UTC, JolanThomassin commented on adr/002-database-structure.md
> +This ADR describes our plan to promote sharing data between software products created by the CFIA AI Lab. At the same time, we aim to make things more flexible and easier to maintain by bringing all
Yeah Ricky told me to do that and I forgot, it's done now

2023-11-08 20:00 UTC, JolanThomassin commented on adr/002-database-structure.md
> +## Optional Illustration
I changed it, but I'm not sure about the results

2023-11-09 14:14 UTC, rngadam requested changes

2023-11-09 14:14 UTC, rngadam commented on adr/002-database-structure.md
> +# ADR 002: ADR on our choices of database structure
# ADR-002: database structure design

2023-11-09 14:14 UTC, rngadam commented on adr/002-database-structure.md
> +Our previous ailab-db architecture required maintenance of several databases, notably "louis-db" and "nachet-db." Although this approach initially provides clarity, it ultimately results in redundanc
I don't see the document wrapped?

2023-11-09 14:14 UTC, rngadam commented on adr/002-database-structure.md
> +- Adapting to the new structure may temporarily complicate the development process.
please research a bit what good industry practices for postgresql / databases

2023-11-09 19:07 UTC, melanie-fressard approved these changes

2023-11-10 13:23 UTC, rngadam requested changes

2023-11-10 13:23 UTC, rngadam commented on adr/002-database-structure.md
> +  https://www.matillion.com/blog/what-is-data-consolidation
could we perhaps extract key quotes from these references into our doc and have that quote linked to the reference here?

2023-11-10 13:23 UTC, rngadam commented on adr/002-database-structure.md
> +![AiLab-db](./002-database-structure-diagram.png)
probably need to finish ADR-008 first so we can reference it here.

Could you try to use ChatGPT image description feature to provide a better alt-text to your images/diagrams?

2023-11-10 14:52 UTC, JolanThomassin commented on adr/002-database-structure.md
> +  https://www.matillion.com/blog/what-is-data-consolidation
That's a good idea, I'll work on that

2023-11-10 14:53 UTC, JolanThomassin commented on adr/002-database-structure.md
> +![AiLab-db](./002-database-structure-diagram.png)
I don't have this functionality , but I'll ask someone to to that for me.

2023-11-22 13:35 UTC, rngadam commented
@JolanThomassin this is still pending changes, we should get it fixed and have the team review it.

2023-11-22 15:28 UTC, JolanThomassin reviewed
Here is the needed modification, I'm going to add the other for review now.

2023-11-22 16:26 UTC, k-allagbe requested changes
Don't forget to update the `index.md` file. A rebase might be needed for that.

2023-11-22 16:26 UTC, k-allagbe commented on adr/002-database-structure.md
> +- [Toptal - Database Design Bad Practices: Are You Making These Mistakes?](https://www.toptal.com/database/database-design-bad-practices)
We agreed to use APA for references. Check https://github.com/ai-cfia/dev-rel-docs/blob/main/adr/001-ailab-using-adr.en-ca.md#format

2023-11-22 20:24 UTC, RussellJimmies requested changes

2023-11-22 20:24 UTC, RussellJimmies commented on adr/002-database-structure.md
> +- **Potential data conflicts:** Separate databases may result in data conflicts, especially when different teams or products need to update the same data simultaneously. These conflicts can lead to d
In-text citations should be linked to the detailed citations in the References section.
 
![image](https://github.com/ai-cfia/dev-rel-docs/assets/88112401/00a6ee55-df8a-4f38-93d9-16e21defe24b)

2023-11-22 20:49 UTC, rngadam commented on adr/002-database-structure.md
> +![AiLab-db](./002-database-structure-diagram.png)
I tried with the builtin Windows Narrator but was defeated by its complicated keybindings and navigation.

2023-11-22 20:53 UTC, rngadam commented on adr/002-database-structure.md
> +# ADR 002: ADR on our choices of database structure
Sorry, should be:

# ADR-002: Database Structure Design

2023-11-23 14:33 UTC, JolanThomassin reviewed
Now it should follow the other one on reference.

2023-11-23 14:33 UTC, JolanThomassin commented on adr/002-database-structure.md
> +- [Toptal - Database Design Bad Practices: Are You Making These Mistakes?](https://www.toptal.com/database/database-design-bad-practices)
I changed it for APA, like in the ADR-005.

2023-11-23 14:33 UTC, JolanThomassin commented on adr/002-database-structure.md
> +- **Potential data conflicts:** Separate databases may result in data conflicts, especially when different teams or products need to update the same data simultaneously. These conflicts can lead to d
Now it's a reference to the end of the page reference.

2023-11-23 14:33 UTC, JolanThomassin commented on adr/002-database-structure.md
> +- [Toptal - Database Design Bad Practices: Are You Making These Mistakes?](https://www.toptal.com/database/database-design-bad-practices)
What is `index.md`?

2023-11-23 14:35 UTC, JolanThomassin commented on adr/002-database-structure.md
> +# ADR 002: ADR on our choices of database structure
It make more sense, modification done! [a91a2dc](https://github.com/ai-cfia/dev-rel-docs/pull/57/commits/a91a2dccff328aaddc346d69e72bbd20d956783e)

2023-11-23 18:53 UTC, rngadam requested changes
document is not wrapping at 80

2023-11-23 21:23 UTC, k-allagbe commented on adr/002-database-structure.md
> +- [Toptal - Database Design Bad Practices: Are You Making These Mistakes?](https://www.toptal.com/database/database-design-bad-practices)
This: https://github.com/ai-cfia/dev-rel-docs/blob/main/adr/index.md

2023-11-23 21:26 UTC, k-allagbe commented on adr/002-database-structure.md
> +- [Toptal - Database Design Bad Practices: Are You Making These Mistakes?](https://www.toptal.com/database/database-design-bad-practices)
This: https://github.com/ai-cfia/dev-rel-docs/blob/main/adr/index.md

2023-11-23 21:28 UTC, k-allagbe requested changes

2023-11-23 21:28 UTC, k-allagbe commented on adr/002-database-structure.md
> +- [Toptal - Database Design Bad Practices: Are You Making These Mistakes?](https://www.toptal.com/database/database-design-bad-practices)
This: https://github.com/ai-cfia/dev-rel-docs/blob/main/adr/index.md

2023-11-24 13:35 UTC, ThomasCardin approved these changes

2023-11-24 17:34 UTC, redat97 approved these changes
nice work !

2023-11-24 19:20 UTC, rngadam requested changes

2023-11-24 19:20 UTC, rngadam commented on adr/002-database-structure.md
> +![The image is a structured diagram titled "CFIA AI Lab Database Structure". It depicts the organization of databases and schemas within the Canadian Food Inspection Agency's AI Lab. At the top of th
Note that the diagram also wrongly uses _v

2023-11-24 19:44 UTC, RussellJimmies approved these changes

2023-11-28 14:18 UTC, JolanThomassin commented on adr/002-database-structure.md
> +- [Toptal - Database Design Bad Practices: Are You Making These Mistakes?](https://www.toptal.com/database/database-design-bad-practices)
I'll add it after the merge

2023-11-28 14:25 UTC, JolanThomassin commented on adr/002-database-structure.md
> +![The image is a structured diagram titled "CFIA AI Lab Database Structure". It depicts the organization of databases and schemas within the Canadian Food Inspection Agency's AI Lab. At the top of th
The diagram was made before the decision, I updated it, now it follow the good version system.

2023-11-28 14:55 UTC, k-allagbe approved these changes

2023-11-29 14:53 UTC, rngadam commented
> document is not wrapping at 80

@JolanThomassin

2023-11-29 19:07 UTC, JolanThomassin commented
> > document is not wrapping at 80
> 
> @JolanThomassin

Yeah I see it and done the change, but for some reason I'm unable to push on it for now. I'll try to fix that ASAP.

![image](https://github.com/ai-cfia/dev-rel-docs/assets/98430140/a5df6693-8452-4546-9a9b-a8f03eb5f384)

2023-11-29 19:13 UTC, JolanThomassin commented
I still have a problem and am not sure why it's happening on my VS Code. However, it seems that my commit was pushed, so everything should be fine! [e21bbe0](https://github.com/ai-cfia/dev-rel-docs/pull/57/commits/e21bbe05294392515a4f99cd6c13dfc5ad5fbf32)

2023-11-30 11:32 UTC, rngadam requested changes

2023-12-04 15:58 UTC, JolanThomassin commented on adr/002-database-structure.md
> +## Context
I have added these 3 ones, and looking if other term need to be explain

2023-12-04 15:58 UTC, JolanThomassin commented on adr/002-database-structure.md
> +Our previous ailab-db architecture required maintenance of several databases,
If we keep using ailab-db for every project, keeping this name sounds good to me. I'm not sure which application you're referring to when you mention the "app schema."

2023-12-05 13:12 UTC, rngadam requested changes

2023-12-05 13:12 UTC, rngadam commented on adr/002-database-structure.md
> +Our previous ailab-db architecture required maintenance of several databases,
what is the use of what we call  louis right now? mostly crawled documents. 

so the schema would be more accurately named docs, and could be used by any number of apps that require to ETL documents  from any source.

2023-12-05 13:12 UTC, rngadam commented on adr/002-database-structure.md
> +## Context
Refer back to our technology for the definitions as those you provided are too generic to be helpful: 

https://www.postgresql.org/docs/current/glossary.html

2024-01-11 16:18 UTC, rngadam requested changes
there's one conversation thread that is unresolved @JolanThomassin

2024-01-15 14:33 UTC, JolanThomassin commented
Indeed, some comments were still pending.  

![image](https://github.com/ai-cfia/dev-rel-docs/assets/98430140/4db05e83-01b1-4ab7-9855-76b9c1555f93)  

Now everything should be answered or resolved.

2024-01-16 19:04 UTC, rngadam commented
@JolanThomassin let's discuss in-person future refactoring of the database to organize by entity types instead of products:

* docs
* people
* logs
* blobs

although the starting point is one db per product, we may want to end up at databases at high-level entities

2024-01-18 15:48 UTC, rngadam approved these changes
As discussed, we will revisit as we rethink consolidation of databases in a new PR

2024-01-18 15:50 UTC, merged