Fixes #45: Mention ADR-004 in index.md
ai-cfia/dev-rel-docs pull request #74
Opened 2023-11-09 14:43 UTC by RussellJimmies

#45

2023-11-10 12:41 UTC, rngadam commented
Have you tested this? If I do view file and click on it I get:

![image](https://github.com/ai-cfia/dev-rel-docs/assets/538542/618f5b95-a474-448a-aad7-518978b3f30e)

...and clearly, the path adr/adr is wrong

2023-11-10 12:41 UTC, rngadam requested changes
Have you tested this? If I do view file and click on it I get:

![image](https://github.com/ai-cfia/dev-rel-docs/assets/538542/618f5b95-a474-448a-aad7-518978b3f30e)

...and clearly, the path adr/adr is wrong

2023-11-10 14:09 UTC, RussellJimmies commented
No I didn't test, I simply followed how it was done initially. This should work now.

2023-11-10 14:12 UTC, rngadam requested changes

2023-11-10 14:12 UTC, rngadam commented on adr/index.md
> +* [ADR-001 - Attachment: ADR Template](./001-ailab-using-adr-template.md) -
do you need ```./``` on your files? by default I think it should be the current directory.

2023-11-10 19:58 UTC, RussellJimmies commented on adr/index.md
> +* [ADR-001 - Attachment: ADR Template](./001-ailab-using-adr-template.md) -
Tested it, didn't work without `./`
Fixed adr-001 links.

2023-11-14 22:04 UTC, RussellJimmies commented
Closed in #78

2023-11-14 22:04 UTC, closed without merging