Issue#75 Write an ADR (008) about naming convention
ai-cfia/dev-rel-docs pull request #77
Opened 2023-11-09 18:23 UTC by JolanThomassin

Name: dev-rel-docs/adr/008-naming-convention.md

Start point: [dev-rel-docs/Naming-Conventions/NAMING-RESOURCES.md at main · ai-cfia/dev-rel-docs (github.com)](https://github.com/ai-cfia/dev-rel-docs/blob/main/Naming-Conventions/NAMING-RESOURCES.md)

2023-11-09 18:56 UTC, JolanThomassin commented
I took the information we obtained at the starting point and added a naming convention for the database. Maybe we can add something about **GitHub issue** and **pull request**?

2023-11-10 13:06 UTC, rngadam requested changes

2023-11-10 13:06 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Example**: `cfia-name`
there's one database server per deployment environment. 

we have to name our deployment environments (such as $USER, dev, uat, prod)

so we probably want to document that too. and we have to decide what the stand should be here for postgres.

for each, we should provide a concrete example

do we want:

* cfia-postgres-rngadam
* cfia-postgres-dev
* cfia-postgres-uat

or a name based on what it provides as a service because the database server could be implemented in a number of postgresql-derived products, such as cosmos or citus or Azure flexible postgresql or our own server:

* cfia-nosql-rngadam
* cfia-nosql-dev
* cfia-nosql-uat

is the cfia prefix helpful? as it's already part of our subscription name? OTOH, we want to make sure our solutions serve the greater needs. And does that create problems by attaching our solutions to our organization only?

2023-11-10 15:01 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Example**: `cfia-name`
With the `cfia` prefix, we encounter the same problem as with the suffix `db`. We don't need them, but they make things clearer in a document or something without context. Honestly, **I don't find them very useful either**, so we can probably remove them, and it will work the same way.

Regarding the choice of the **database server**, the best approach is to be **as precise as possible** because it will define what's underneath. Choosing something like `nosql` can be a better idea.

2023-11-14 14:21 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +consistency and clarity in communication and documentation.
When I explore on the web I found thing similar to what we have for now.

So, I asked ChatGPT to give us some examples, and here's what I got:

**Prompt:**
```
You are an expert in database.
Your goal is to help me generate naming convention for my document.

Give me a naming convention for this :
database server, database, schema,  table and view.
```

**Answer:**
```
Database Server:
Prefix: srv_
Example: srv_production

Database:
Prefix: db_
Example: db_sales

Schema:
Prefix: schema_
Example: schema_hr

Table:
Prefix: tbl_
Example: tbl_employee

View:
Prefix: view_
Example: view_employee_summary
```

2023-11-14 14:21 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Convention**: Use lowercase and separate words with underscore.
For tables and views, I utilize the nomenclature we have for `louis`.

Determining the 'entity' can be hard because it may change, but I believe the optimal approach is to employ the most descriptive term possible. This way, we can instantly discern the content of our tables.

2023-11-14 14:42 UTC, JolanThomassin commented
I think it can be a good idea to add:
- GitHub issue
- GitHub pull request
- Python script
- Azure model
- Azure engine

2023-11-15 14:10 UTC, rngadam commented on adr/008-naming-convention.md
> +consistency and clarity in communication and documentation.
the prefix convention you've got from ChatGPT is pretty bad and redundant for the same reasons we've discussed for other prefixes so ignore that.

2023-11-15 14:11 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Example**: `cfia-name`
we've discussed it in person and the conclusion was to use a codename instead of attaching this to particular organization or product names (that may change as the scope or implementation changes)

2023-11-15 14:14 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Convention**: Use lowercase and separate words with underscore.
the whole purpose of modeling in the relational model is to model the relationship between... entities. 

chunk is an entity, content is entity, embedding is entity... etc. as a rule we'd want the entity name to be singular - that way we don't have to figure out if it's pluralize or not.

2023-11-15 14:14 UTC, rngadam requested changes
added comments to the existing discussions.

2023-11-15 14:40 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Convention**: Use lowercase and separate words with underscore.
Something like this so:
```
Convention: Use lowercase letters and separate words with underscores. Entity names should be in singular form.
Examples:

member
author
chunk
content
embedding
```

2023-11-15 14:48 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Convention**: Use lowercase and separate words with underscore.
**When looking for reference I found this online:**

Plural or Singular Tables?
There's long been a huge debate amongst experts in database theory about whether or not database tables should be singular (customer) or plural (customers). Without going into the theory, let me cut the Gordian Knot with a healthy dose of pragmatism: plural table names are less likely to conflict with reserved keywords.

Do you have users? SQL has a user reserved word. Do you want a table of constraints? constraint is a reserved word. Is audit a reserved word but you want an audit table? By simply using the plural form of nouns, most reserved words won't cause you grief when you're writing SQL. I've even tripped up PostgreSQL, which has an excellent SQL parser, when I've had a user table and later, an ORM automatically aliased that to user (yes, the same name) and PostgreSQL got confused.

Just use plural names and you're far less likely to have a collision.

https://dev.to/ovid/database-naming-standards-2061

2023-11-15 14:59 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +consistency and clarity in communication and documentation.
Here is a set of good references I found, I'll add them soon to the document

**Naming for database:**
https://dev.to/ovid/database-naming-standards-2061
https://github.com/RootSoft/Database-Naming-Convention
https://vertabelo.com/blog/database-naming-convention/

**Naming for GitHub:**
https://tilburgsciencehub.com/building-blocks/collaborate-and-share-your-work/use-github/naming-git-branches/
https://gist.github.com/digitaljhelms/4287848

**Naming for Azure:**
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming
https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations

2023-11-15 15:03 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Example**: `cfia-name`
**Database Server / Cluster**
_Convention_: Start with a codename followed by the name in lowercase, separating words with dashes.
**Example:** codename-name
**Example:** nachet-postgresql
**Example:** cosmos-nosql-jolanthomassin

2023-11-15 16:08 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Convention**: Use lowercase and separate words with underscore.
@JolanThomassin interesting argurment for pluralized form!

2023-11-17 16:25 UTC, melanie-fressard requested changes
Good job, it's great to finally have this document !
Minor suggestions and I'm good with it

2023-11-17 16:25 UTC, melanie-fressard commented on adr/008-naming-convention.md
> +The decision to establish a Naming Convention for the Artificial Intelligence
not sure if the caps on naming convention is necessary

2023-11-17 16:25 UTC, melanie-fressard commented on adr/008-naming-convention.md
> +(AI) Lab aims to bring clarity and consistency to the lab's internal structure.
You have to write laboratory entirely before just Lab + maybe precise that it's CFIA lab

2023-11-17 16:25 UTC, melanie-fressard commented on adr/008-naming-convention.md
> +- **Convention**: Use prefix with date format YYYY-mm-dd followed by a
you can put yyyy in lowercase here

2023-11-17 16:25 UTC, melanie-fressard commented on adr/008-naming-convention.md
> +# ADR-008 : Naming Convention for AI Lab
covention doesn't need an uppercase. I was also thinking maybe we should put it in plurals since there is more than one convention

2023-11-17 16:25 UTC, melanie-fressard commented on adr/008-naming-convention.md
> +within the AI Lab, making it easier for researchers, developers, and other to
others*

2023-11-17 19:06 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +# ADR-008 : Naming Convention for AI Lab
I added the plural, for the title, this is volontary, this is called 'title case"


Title case is often used in titles, headlines, or headings to enhance readability and visual appeal. It helps to distinguish important words in the title, such as nouns, verbs, adjectives, and adverbs, by capitalizing their initial letters.

2023-11-17 19:06 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +The decision to establish a Naming Convention for the Artificial Intelligence
Indeed there is no need here. I removed caps

2023-11-17 19:06 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +(AI) Lab aims to bring clarity and consistency to the lab's internal structure.
Changed done!

2023-11-17 19:06 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Convention**: Use prefix with date format YYYY-mm-dd followed by a
this is better like this, changed made

2023-11-17 19:06 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Convention**: Use lowercase and separate words with underscore.
I choose plural for now, I'll need to see other opinion on that.

2023-11-17 19:06 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +within the AI Lab, making it easier for researchers, developers, and other to
thanks!

2023-11-17 21:12 UTC, melanie-fressard commented on adr/008-naming-convention.md
> +# ADR-008 : Naming Convention for AI Lab
Thank you for this precision !

2023-11-17 21:13 UTC, melanie-fressard approved these changes
Good for me after these changes ! Good job !

2023-11-17 21:13 UTC, melanie-fressard commented on adr/008-naming-convention.md
> +(AI) of the CFIA Laboratory (lab) aims to bring clarity and consistency to the lab's internal structure.
You need to write what CFIA stand for

2023-11-17 21:13 UTC, melanie-fressard commented on adr/008-naming-convention.md
> +The establishment of a Naming Convention for the Artificial Intelligence (AI)
No need for (AI) here

2023-11-20 12:16 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Example**: `cfia-name`
using the codename fixes not attaching it to the organization, yes.

nachet-postgresql is fine but we also probably need to postfix with which environment it is in (nachet-postgresql-jolanthomassin, nachet-postgresql-dev, nachet-postgresql-uat, nachet-postgresql-prod)

cosmos-nosql-jolanthomassin as an example looks completely different though; cosmos is a Microsoft product name, nosql is a class of solution. it's not consistent with what we're proposing).

2023-11-20 14:00 UTC, k-allagbe approved these changes

2023-11-20 22:45 UTC, redat97 approved these changes
nice work !

2023-11-22 20:39 UTC, RussellJimmies requested changes

2023-11-22 20:39 UTC, RussellJimmies commented on adr/008-naming-convention.md
> +intelligence research and development.
I would say "... and structured practices in the field of **applied AI**" instead of "AI R&D".

2023-11-22 20:39 UTC, RussellJimmies commented on adr/008-naming-convention.md
> +- **Convention**: Start with `rg-` followed by the name in lowercase, separating
I would end with "-rg". Reads better. (Nachet Resource Group vs. Resource Group Nachet)

2023-11-22 20:56 UTC, rngadam requested changes

2023-11-22 20:56 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Example**: `name_v1.0.0`
the v is not part of the ADR-006 as we've seen

2023-11-23 14:41 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +(AI) of the CFIA Laboratory (lab) aims to bring clarity and consistency to the lab's internal structure.
You're right, done!

2023-11-23 14:42 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +intelligence research and development.
It's shorter and still make sense, sound good for me. Modification done!

2023-11-23 14:42 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +The establishment of a Naming Convention for the Artificial Intelligence (AI)
You're right, I removed it.

2023-11-23 14:44 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Convention**: Start with `rg-` followed by the name in lowercase, separating
I believe it's a better idea to have it in front so that if we have a long name, we can see it properly and immediately know what it is.

Like this: `rg-this-is-a-super-long-ressource-group-name`

2023-11-23 14:50 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Example**: `name_v1.0.0`
You are right, I don't know why he is here, it's removed!

2023-11-23 19:07 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Example**: `cfia-name`
project-service-environment yeah, with examples of project values, service values, environment values.

2023-11-23 19:08 UTC, rngadam commented on adr/008-naming-convention.md
> +consistency and clarity in communication and documentation.
@JolanThomassin I think still waiting on these refs to be added and used.

2023-11-23 19:08 UTC, rngadam requested changes
waiting for a reply on every conversations thread from @JolanThomassin

2023-11-24 13:38 UTC, ThomasCardin approved these changes
lgtm

2023-11-24 19:41 UTC, RussellJimmies commented on adr/008-naming-convention.md
> +- **Convention**: Start with `rg-` followed by the name in lowercase, separating
When you're browsing resource groups on Azure, you know they're resource groups. Ordering alphabetically becomes an eye sore when they all start by rg-
![image](https://github.com/ai-cfia/dev-rel-docs/assets/88112401/e786f167-5b9e-4e76-9cd1-1eac2330b552)

2023-11-27 19:04 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +consistency and clarity in communication and documentation.
Ok, they should be add.

2023-11-27 21:51 UTC, rngadam requested changes

2023-11-27 21:51 UTC, rngadam commented on adr/008-naming-convention.md
> +(AI) of the Canadian Food Inspection Agency (CFIA) Laboratory aims to bring clarity and consistency to the lab's internal structure.
seems this is the wrapping properly

2023-11-27 21:51 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Convention**: Start with `name_v` where name is the Schema name, followed by the current version numbers.
there's no v?

2023-11-27 21:51 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Why**: SQL reserved word are singular, so by using plural you're less likely to have a collision.
I like that you have a why here. we probably should keep a why for every convention

2023-11-27 21:51 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Example**: `nachet-postgresql-dev`
we also need to document the abbreviation for environments under another heading

* dev: development environment (typically ongoing development branches deployed for developer testing)
* uat: user-acceptance testing: new version that is shared to product management and champion users for testing before deployment to production
* prd: production: production version of the system

this is also part of ongoing discussions with @redat97 on deploying frontends/backends to different environments.

2023-11-28 19:30 UTC, RussellJimmies approved these changes

2023-11-29 13:02 UTC, k-allagbe requested changes

2023-11-29 13:02 UTC, k-allagbe commented on adr/008-naming-convention.md
> +- **Example**: `nachet-postgresql-dev`
The convention mentions a `cfia-` prefix but the examples don't have it.

2023-11-29 19:04 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Why**: SQL reserved word are singular, so by using plural you're less likely to have a collision.
I add one on Database Schema versioning after the conversation we got about `semver`. I'll add some others "why" later on the other topics if I get more information.

2023-11-29 19:25 UTC, rngadam commented
> lgtm

@ThomasCardin expecting a bit more input on this ADR as you need to develop additional naming conventions also for our IaC.

2023-11-29 20:30 UTC, k-allagbe approved these changes

2023-11-30 11:18 UTC, rngadam requested changes

2023-11-30 11:22 UTC, rngadam requested changes
additional comments added in source

2023-12-04 17:31 UTC, k-allagbe reviewed
React considerations for env vars.

2023-12-04 17:31 UTC, k-allagbe commented on adr/008-naming-convention.md
> +- **Example**: `PROJECT_NAME_MY_ENV_VAR`
In react projects, the env vars have to be prefixed with `REACT_APP_` to be valid. How do we handle this? 

I would suggest `REACT_APP_PROJECT_NAME_MY_ENV_VAR`.

2023-12-04 18:41 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Example**: `PROJECT_NAME_MY_ENV_VAR`
Maybe we can add an exception text for that.

2023-12-04 19:18 UTC, k-allagbe commented on adr/008-naming-convention.md
> +- **Example**: `PROJECT_NAME_MY_ENV_VAR`
Yes an exception text would be good.
@rngadam @CFIALeronB please share your thoughts on this.

2023-12-05 13:22 UTC, rngadam requested changes

2023-12-05 13:22 UTC, rngadam commented on adr/008-naming-convention.md
> +- **Example**: `PROJECT_NAME_MY_ENV_VAR`
sure, should be documented here

2023-12-05 13:22 UTC, rngadam commented on adr/008-naming-convention.md
> +  words with dashes. `-rg` stand for `ressource group`.
ressource is resource in english

2023-12-14 15:53 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +- **Example**: `PROJECT_NAME_MY_ENV_VAR`
I add a little text for this exception

2023-12-14 15:53 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +  words with dashes. `-rg` stand for `ressource group`.
Issue fixed!

2023-12-14 15:53 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +  `project-service-environment` all in lowercase, separating words with dashes.
I added this at the top, it's short but I think it's a good way to resume it.

2023-12-14 18:45 UTC, k-allagbe approved these changes

2023-12-14 21:04 UTC, melanie-fressard commented on adr/008-naming-convention.md
> +## Notes
well we used to have louis-db but the repo wasn't only for louis-db, so maybe put a line saying that names should have something to do with what they're for

2023-12-15 14:57 UTC, JolanThomassin commented on adr/008-naming-convention.md
> +## Notes
I added it 👍

2023-12-21 14:26 UTC, merged

2023-12-21 16:36 UTC, k-allagbe commented
@JolanThomassin this PR is merged with one unresolved comment.

2024-01-11 16:20 UTC, rngadam commented
(I apparently had pending requests that were not submitted before it is merged)