Fixes #85: Write an ADR about the infrastruture
ai-cfia/dev-rel-docs pull request #86
Opened 2023-12-15 19:05 UTC by ThomasCardin

2024-01-10 14:43 UTC, rngadam requested changes
* Not sure why the checks pass here, we're supposed to be checking for markdown line length to be wrapping at 80
* choose one language and write the file for that and then translate as a final step, don't have both files in (especially since they are out of sync - and then I don't know why one we should be reviewing.

2024-01-10 20:13 UTC, rngadam requested changes

2024-01-10 20:13 UTC, rngadam commented on adr/010-infrastructure.fr-ca.md
> +Le scalling de nos applications n'est pas actuellement une priorité, car nous avons une visibilité fixe sur le nombre d'utilisateurs. Cependant, nous n'avons pas encore mis en oeuvre de solution de s
scaling

2024-01-10 20:13 UTC, rngadam commented on adr/010-infrastructure.fr-ca.md
> +En ce qui concerne le monitoring et la télémétrie, nous n'avons actuellement rien en place en dehors des outils fournis par les fournisseurs de cloud. Nous reconnaissons la nécessité d'améliorer ces
hmmm, les solutions de monitoring et de logging et de télémétrie de Google Cloud Run (ce que j'ai essayé) sont très sophistiqués en fait. je vois mal comment les solutions maisons (avec leur coût de maintien) font mieux. Dans le meilleur des cas, elles sont compétitives avec les solutions built-in dans les infonuages.

2024-01-10 20:13 UTC, rngadam commented on adr/010-infrastructure.fr-ca.md
> +Bref, de nombreuses tâches sont actuellement effectuées manuellement. Bien que nous disposions de github workflow pour déployer des images Docker, la gestion des déploiements sur différents fournisse
Github Workflow, d'infonuages

2024-01-10 20:13 UTC, rngadam commented on adr/010-infrastructure.fr-ca.md
> +Voici quelle que cas d'utilisations qui on été discuter qu'on voudrait gérer:
c'est une phrase un peu longue pour dire:

Cas d'utilisations

qui pourrait être son propre en-tête

2024-01-10 20:13 UTC, rngadam commented on adr/010-infrastructure.fr-ca.md
> +- Mettre en place des déploiements sur tous les fournisseurs de cloud en cas de pannes. Cela inclue une persistances des données dans les différents cloud provider ;
une persistence ... fournisseurs d'infonuages

2024-01-10 20:13 UTC, rngadam commented on adr/010-infrastructure.fr-ca.md
> +- Créer une documentation facile de lecture et d'adaption pour permettre une transition "shift-left" ;
explique shift-left

2024-01-10 20:13 UTC, rngadam commented on adr/010-infrastructure.fr-ca.md
> +- Gestion des VM's (au besoins): KubeVirt ;
machine virtuelles, au besoin

2024-02-15 16:31 UTC, rngadam commented
@ThomasCardin @SonOfLope are we following up on this?

2024-02-15 18:22 UTC, SonOfLope commented
> @ThomasCardin @SonOfLope are we following up on this?

@ThomasCardin correct me if I'm wrong but we agreed we were gonna take our time on writing this since some of the structure hasn't been fully implemented yet. We're following up on it as we work on Howard. I will convert it in draft.

2024-03-21 18:14 UTC, rngadam requested changes
good, we're keeping track of the different solutions we tried and have documentation. 

can we add links to the canonical website for each solution?

2024-04-05 18:37 UTC, rngadam requested changes

2024-04-05 18:37 UTC, rngadam commented on adr/011-gitops.fr-ca.md
> +# ADR-011 : GitOps
Il me semble que le terme GitOps englobe un espace plus large que le déploiement d'applications?

argocd "Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes."

donc le sujet devrait plutôt être continuous delivery / livraison continu? et englober dans la comparaison des options Github Actions et Azure Pipelines?

2024-04-05 18:37 UTC, rngadam commented on adr/010-infrastruture.en-ca.md
> +# ADR-XXX : Title
typo 010-infrastructure.en-ca.md

2024-04-10 20:38 UTC, SonOfLope commented on adr/014-containers.fr-ca.md
> +manuellement les conteneurs était fastidieux et sujet à des erreurs. De plus,
Faudrait peut-être préciser initialement on déployait où les conteneurs. En soit on a encore des répertoires avec Dockerfile.

2024-04-19 17:14 UTC, MaxenceGui approved these changes
LGTM, just a few language mistake to correct

2024-04-19 17:29 UTC, ibrahim-kabir approved these changes
Incredible work.

2024-04-22 13:20 UTC, SonOfLope commented on .vscode/settings.json
done!

2024-04-22 13:26 UTC, ThomasCardin commented on adr/016-networking.fr-ca.md
> +Cette ADR vise à formaliser la stratégie de réseautique pour nos applications
Done, je viens de changer pour  "cette décision d'architecture"

2024-04-23 18:06 UTC, k-allagbe approved these changes

2024-04-23 18:13 UTC, SonOfLope approved these changes

2024-05-01 18:48 UTC, merged