Fixes 7 : Introduction redat97
ai-cfia/dev-rel-docs pull request #9
Opened 2023-09-05 15:10 UTC by redat97

2023-09-05 16:50 UTC, rngadam commented
@redat97 

Maybe rework a bit the text, don't forget that this will be also visible to the public so should sound more like a work profile and also include an outline of your responsabilities.

also your commit "Fixes 7" needs to be "Fixes #7" to work...

2023-09-05 16:50 UTC, rngadam requested changes
see comment

2023-09-11 18:56 UTC, rngadam requested changes

2023-09-11 18:56 UTC, rngadam commented on README.md
> +ajouter nom et description au readMe (markdown spepare avec link dans readme)
what's this?

2023-09-11 19:58 UTC, redat97 commented on README.md
> +ajouter nom et description au readMe (markdown spepare avec link dans readme)
Notes I took because at the first idea was to include the name of the developer then a link to the presentation but I will get it sorted now

2023-09-11 20:13 UTC, rngadam requested changes

2023-09-11 20:13 UTC, rngadam commented on README.md
> +Happy developing!
it's best to completely revert README.md to the main version because your change in that file seems to not be an actual change (trailing whitespace? linefeed?) and has nothing to do with your PR.

2023-09-11 20:29 UTC, rngadam requested changes
You

2023-09-11 20:30 UTC, rngadam requested changes

2023-09-11 20:30 UTC, rngadam commented on reda-tarzalt-introduction.md
> +LinkedIn : https://ca.linkedin.com/in/reda-tarzalt-14b8171a2
fix your URL to remove the generated string at the end:

![image](https://github.com/ai-cfia/dev-rel-docs/assets/538542/da9bbefc-db11-4233-9f9f-6ae5f578f84c)

https://www.linkedin.com/public-profile/settings?trk=d_flagship3_profile_self_view_public_profile

2023-09-11 20:35 UTC, rngadam requested changes
please answer the comment in the previous review

2023-09-11 20:37 UTC, redat97 commented on reda-tarzalt-introduction.md
> +LinkedIn : https://ca.linkedin.com/in/reda-tarzalt-14b8171a2
On it !

2023-09-11 20:38 UTC, redat97 commented on README.md
> +Happy developing!
Ok I will revert the file now

2023-09-11 20:41 UTC, rngadam commented on reda-tarzalt-introduction.md
> +LinkedIn : https://ca.linkedin.com/in/reda-tarzalt-14b8171a2
I don't see the fix

2023-09-11 20:41 UTC, rngadam requested changes
make sure you've pushed your changes before requesting a review

2023-09-11 20:47 UTC, rngadam approved these changes

2023-09-11 20:52 UTC, merged