issue #98: Started writing post-mortems
ai-cfia/dev-rel-docs pull request #99
Opened 2024-01-19 16:11 UTC by ThomasCardin

- Post mortem write up that occured yesterday

2024-01-22 18:54 UTC, SonOfLope commented on postmortems/incident-1.md
> +par etapes.
suggestion : Add in lesson learned that testing earlier if the app is working locally compared to the deployment in production  would of helped find the problem sooner ?

2024-01-22 19:17 UTC, SonOfLope approved these changes

2024-01-22 20:46 UTC, rngadam requested changes

2024-01-22 20:46 UTC, rngadam commented
@ThomasCardin developers should be included as reviewers.

2024-01-23 19:53 UTC, MaxenceGui commented on postmortems/incident-1.md
> +- We had to take our time to explain the various components of the Nachet system,
Line 74: We had to take our time to explain the various components of the Nachet system.

Do you guys mean explore instead of explain?

2024-01-23 20:21 UTC, rngadam requested changes

2024-01-23 20:21 UTC, rngadam commented on postmortems/incident-1.md
> +We couldn't load and classify any images using the Azure AI Model.
provide frontend symptoms (screenshots) - browser-side errors

2024-01-23 20:21 UTC, rngadam commented on postmortems/incident-1.md
> +# Nachet backend classification not working (incident #1)
consider as a system. This is Nachet Interactive deployed to Kubernetes was not working as a whole. that's the user-visible impact.

2024-01-23 20:21 UTC, rngadam commented on postmortems/incident-1.md
> +Around 200$ lost
details

2024-01-23 20:21 UTC, rngadam commented on postmortems/incident-1.md
> +- The time of developers and DevSecOps personnel.
how about my time? how about reputation lost with the customer?

2024-01-23 20:21 UTC, rngadam commented on postmortems/incident-1.md
> +Before searching for the perfect solution to the error, proceed step by step.
Manual testing to detect the issue earlier?

2024-01-23 20:21 UTC, rngadam commented on postmortems/incident-1.md
> +did not take much time.
quantify turn around time. don't forget there was two problems

2024-01-23 20:21 UTC, rngadam commented on postmortems/incident-1.md
> +## Timeline
timezone Eastern Standard Time

2024-01-23 20:21 UTC, rngadam commented on postmortems/incident-1.md
> +**2023-01-12 (14:00):** The application has been deployed. The frontend can
how was this validated

2024-01-23 20:21 UTC, rngadam commented on postmortems/incident-1.md
> +**2023-01-10 (14:00):** A request has been made for the application to
dates should be 2024

2024-01-23 20:21 UTC, rngadam commented on postmortems/incident-1.md
> +
2024-01-17 (13:21): link to deployed system https://nachet.ninebasetwo.xyz/ is provided to the analysts for review

2024-02-15 16:33 UTC, rngadam commented
@ThomasCardin dates are still incorrect

2024-02-15 19:07 UTC, ThomasCardin commented
> @ThomasCardin dates are still incorrect

Done

2024-02-16 13:40 UTC, rngadam commented
There's a large number of my comments that were not adressed. I suggest we spin off a checklist of these comments in another issue to postpone the work and get this PR merged in.

2024-02-27 19:28 UTC, ThomasCardin commented
Okay, will do. Can we merge this one tho? @rngadam

2024-03-12 13:52 UTC, ThomasCardin commented
> There's a large number of my comments that were not adressed. I suggest we spin off a checklist of these comments in another issue to postpone the work and get this PR merged in.

For comments that you think they are not resolved yet. Can you open an issue so we can merge this PR.

2024-03-19 17:56 UTC, rngadam requested changes
Left one change that I want addressed before we merge. Closed the other ones. 

In the future, it's up to the person doing the PR to open additional issues since they are the ones postponing the work.

2024-03-19 17:56 UTC, rngadam commented on postmortems/incident-1.md
> +[stack trace](https://bit.ly/3ScnqCk)
please fix this one before merging

2024-03-28 20:43 UTC, rngadam approved these changes

2024-03-28 20:45 UTC, rngadam requested changes
Github Workflow lint fails: https://nachet.ninebasetwo.xyz/ needs to be removed as a link (maybe just turn it into plain text so it doesn't trip the markdown checker.

2024-04-02 20:47 UTC, rngadam approved these changes

2024-04-03 19:22 UTC, merged